---
title: "Comparing p-tau217/AB42 to CSF using FDA cutoffs"
format: html
editor: visual
number-sections: true
---

# Comparing p-tau217/AB42 to CSF using FDA cutoffs

#### Load libraries

```{r load libraries}
library(readxl)
library(tidyverse)
library(pROC)
library(boot)
library(gtsummary)
library(ggpubr)
library(ggbeeswarm)
library(pROC)
library(see)
```

# 1. BioFINDER-Memory Clinic

------------------------------------------------------------------------

```{r set up data BF-MC}
#| echo: false
df <- read_xlsx("~/d1.xlsx")
```

## 1A. VR outcome

### Boxplots VR (BFMC)

```{r boxplots VR BFMC}
df$petstat <- as.factor(df$VR_overall)

ggplot(df, aes(x = petstat, y = PL_217_42, fill=petstat)) +
  annotate("rect", xmin = -Inf, xmax = Inf, ymin = 0.0037, ymax = 0.0074,
           fill = "grey80", alpha = 0.4) +
  geom_violin(alpha=0.3) +
  geom_hline(yintercept=0.00738, linetype="dashed", color="grey20", alpha=.8, linewidth = .35) +
  geom_hline(yintercept=0.0037, linetype="dashed", color="grey20", alpha = .8, linewidth = .35) +
  geom_quasirandom(alpha = 0.75, size = 1,shape=21, color="black", stroke=0.25) +
  scale_y_continuous(breaks = round(seq(0, 0.1, by = 0.025), 3), limits = c(0, 0.085)) +
  scale_x_discrete(labels=c("0" ="VR-","1" ="VR+")) +
  labs(x = "AD status", y = "Plasma p-tau217/AB42") +
  scale_fill_manual(values = c("#afafaf", "#c52851"), guide = "none") +
  theme_classic() +
  theme(axis.title.x = element_blank(),
        axis.title.y = element_text(size=7),
        axis.text.x = element_text(size=6),
        axis.text.y = element_text(size=6))+
  stat_compare_means(method="t.test", label="p.signif", label.x = 1.5, label.y = 0.04)

##CSF
ggplot(df, aes(x = petstat, y = csf_4240, fill=petstat)) +
  annotate("rect", xmin = -Inf, xmax = Inf, ymin = 0.058, ymax = 0.072,
           fill = "grey80", alpha = 0.4) +
  geom_violin(alpha=0.3) +
  geom_hline(yintercept=0.058, linetype="dashed", color="grey20", alpha=.8, linewidth = .35) +
  geom_hline(yintercept=0.072, linetype="dashed", color="grey20", alpha = .8, linewidth = .35) +
  geom_quasirandom(alpha = 0.75, size = 1,shape=21, color="black", stroke=0.25) +
  scale_x_discrete(labels=c("0" ="VR-","1" ="VR+")) +
  labs(x = "AD status", y = "CSF AB42/40") +
  scale_fill_manual(values = c("#afafaf", "#295dbf"), guide = "none") +
  theme_classic() +
  theme(axis.title.x = element_blank(),
        axis.title.y = element_text(size=7),
        axis.text.x = element_text(size=6),
        axis.text.y = element_text(size=6))+
  stat_compare_means(method="t.test", label="p.signif", label.x = 1.5, label.y = 0.04)

```

### Analyses VR AUC (BFMC)

```{r BFMC,AB-PET VR outcome}
##AUC differences with DeLong
df$petstat <- as.factor(df$VR_overall)

#| echo: false
biomarkers <- c("PL_217_42","ptau217", "csf_4240")
results_delong <- list()
index <- 1

library(pROC)

for (i in seq_along(biomarkers)){
  for (j in seq_along(biomarkers)){ 
    if (i < j) {
      predictor1 <- biomarkers[i]
      predictor2 <- biomarkers[j]
      
      formula1 <- as.formula(paste("petstat~",predictor1, collapse=""))
      formula2 <- as.formula(paste("petstat~",predictor2, collapse=""))
      
      roc_curve1 <- pROC::roc(formula1, data=df, quiet=T)
      roc_curve2 <- pROC::roc(formula2, data=df,quiet=T)
      
      res <- roc.test(roc_curve1, roc_curve2, method = "delong")
      
      long <- data.frame(
        comp = paste(predictor1, predictor2, sep=" vs. "),
        auc1a = round(roc_curve1$auc,3),
        auc2a = round(roc_curve2$auc,3),
        pval = round(res$p.value,3),
        auc1_ci_low = round(ci.auc(roc_curve1)[1],3),
        auc1_ci_high =round(ci.auc(roc_curve1)[3],3),
        auc2_ci_low =round(ci.auc(roc_curve2)[1],3),
        auc2_ci_high = round(ci.auc(roc_curve2)[3],3)
      )
      
      results_delong[[length(results_delong) + 1]] <- long
      index <- index + 1
    }
  }
}

results_delong <- do.call(rbind.data.frame, results_delong)
results_delong$padj <- round(p.adjust(results_delong$pval, method = "fdr"),3)
results_delong$auc_order <- c(results_delong$auc1a[1],results_delong$auc1a[3], results_delong$auc2a[3])
results_delong$auc_order_ci_low <- c(results_delong$auc1_ci_low[1],results_delong$auc1_ci_low[3], results_delong$auc2_ci_low[3])
results_delong$auc_order_ci_high <- c(results_delong$auc1_ci_high[1],results_delong$auc1_ci_high[3], results_delong$auc2_ci_high[3])
openxlsx::write.xlsx(results_delong,
                     file="~/DELONG_VR.xlsx")

##AUC plot
roc_curve2 <- pROC::roc(petstat ~ ptau217, data=df,quiet=T)
auc2 <- auc(roc_curve2)
roc_curve1 <- pROC::roc(petstat ~ PL_217_42, data=df,quiet=T)
auc1 <- auc(roc_curve1)
roc_curve3 <- pROC::roc(petstat ~ csf_4240, data=df,quiet=T)
auc3 <- auc(roc_curve3)

roc_list <- list(roc_curve1, roc_curve2, roc_curve3)

ggroc(roc_list) +
  scale_color_manual(values = c("#c52851", "#4ca481", "#295dbf"), 
                     labels = c("Plasma p-tau217/AB42", "Plasma p-tau217", "CSF AB42/40"), guide="none") +
  labs(title = element_blank(), x = "Specificity", y = "Sensitivity", color = "Assay") +
  scale_x_reverse()+
  scale_y_continuous()+
  geom_abline(slope = 1, intercept = 1, linetype = "dashed") +
  theme_classic()+
  theme(panel.border = element_blank(),
        axis.text.y = element_text(size = 5,color="grey30"),
        axis.text.x = element_text(size = 5,color="grey30"),
        axis.title.x = element_text(size=6,color="black"),
        axis.title.y = element_text(size=6),color="black")+
  annotate("text", x=0.3, y=0.25, 
           label = sprintf("%.2f (%.2f, %.2f)", auc(roc_curve1), ci.auc(roc_curve1)[1], ci.auc(roc_curve1)[3]),
           size = 2, color = "#c52851")+
  annotate("text", x=0.3, y=0.15, 
           label = sprintf("%.2f (%.2f, %.2f)", auc(roc_curve2), ci.auc(roc_curve2)[1], ci.auc(roc_curve2)[3]),
           size = 2, color = "#4ca481")+
  annotate("text", x=0.3, y=0.05, 
           label = sprintf("%.2f (%.2f, %.2f)", auc(roc_curve3), ci.auc(roc_curve3)[1], ci.auc(roc_curve3)[3]),
           size = 2, color = "#295dbf")

```

### Metrics VR (BFMC)

```{r metrics BFMC}
#| echo: false

df$petstat <- as.factor(df$VR_overall)

df$ptau217ab42_pos <- ifelse(df$PL_217_42 >= 0.00738, 1, 0) 
df$ptau217ab42_neg <- ifelse(df$PL_217_42 <= 0.00370, 0, 1)


df$ab4240_pos <- ifelse(df$csf_4240 <= 0.072, 1, 0)
df$ab4240_pos2 <- ifelse(df$csf_4240 <= 0.058, 1, 0)

##Calculate Accuracy, PPV, NPV and 95% CIs

f_comp_stats <- function(data, indices) {
  d <- as.data.frame(data[indices,])
  
  ##threshold calculation related to d, and then assign binary status based on that threshold
  compute_metrics <- function(true, pred) {
    
    ##threshold calculation and 
    
    v_tp <- sum(true == 1 & pred == 1)
    v_fp <- sum(true == 0 & pred == 1)
    v_tn <- sum(true == 0 & pred == 0)
    v_fn <- sum(true == 1 & pred == 0)
    
    sens <- v_tp / (v_tp + v_fn)
    spec <- v_tn / (v_tn + v_fp)
    acc <- (v_tp + v_tn) / (v_tp + v_tn + v_fn + v_fp)
    ppv <- cutpointr::ppv(tp = v_tp, fp = v_fp, tn = v_tn, fn = v_fn)
    npv <- cutpointr::npv(tp = v_tp, fp = v_fp, tn = v_tn, fn = v_fn)
    
    return(c(acc, ppv, npv, sens, spec, v_tp, v_fp, v_tn, v_fn))
  }
  
  test_columns <- c("ptau217ab42_pos", "ab4240_pos")
  results <- matrix(nrow = length(test_columns), ncol = 9)
  colnames(results) <- c("Accuracy", "PPV", "NPV", "Sensitivity", "Specificity", "TP", "FP", "TN", "FN")
  rownames(results) <- c("PL_217_42", "csf_4240")
  
  for (i in seq_along(test_columns)) {
    results[i, ] <- round(compute_metrics(d$petstat, d[[test_columns[i]]]),3)
  }
  
  #Assign p-tau217/AB42 metrics
  acc1 <- results[1,1]
  ppv1 <- results[1,2]
  npv1 <- results[1,3]
  sens1 <- results[1,4]
  spec1 <- results[1,5]
  tp1 <- results[1,6]
  fp1 <- results[1,7]
  tn1 <- results[1,8]
  fn1 <- results[1,9]
  
  #Assign CSF metrics
  acc2 <- results[2,1]
  ppv2 <- results[2,2]
  npv2 <- results[2,3]
  sens2 <- results[2,4]
  spec2 <- results[2,5]
  tp2 <- results[2,6]
  fp2 <- results[2,7]
  tn2 <- results[2,8]
  fn2 <- results[2,9]
  
  #p-tau217 vs. 217/ab42
  diff_acc <- acc1 - acc2
  diff_ppv <- ppv1 - ppv2
  diff_npv <- npv1 - npv2
  diff_sens <- sens1 - sens2

  
  return(c(acc1, acc2, ppv1, ppv2, npv1, npv2,#6
           diff_acc, diff_ppv, diff_npv, diff_sens,#10
           sens1, sens2, spec1, spec2, diff_sens, #15
           tp1, fp1, tn1, fn1, tp2, fp2, tn2, fn2)) #23
}   

set.seed(12345)
boot_results <- boot(data = df, statistic = f_comp_stats, R = 2000)

#Calculate pvalues 1 cutoff
stat_indices <- list(
  "Accuracy 217_AB42 vs. CSF" = 7,
  "PPV 217_AB42 vs. CSF" = 8,
  "NPV 217_AB42 vs. CSF" = 9)

pvals_1cp <- data.frame(
  Pval = numeric(length(stat_indices)),
  row.names = c("Accuracy 217_AB42 vs. CSF","PPV 217_AB42 vs. CSF","NPV 217_AB42 vs. CSF"))

bootstrap_replicates <- boot_results$t
for (stat_name in names(stat_indices)) {
  index <- stat_indices[[stat_name]]
  boot_diff <- boot_results$t0[index]
  results_underH0_diff <- bootstrap_replicates[, index] - mean(bootstrap_replicates[, index])
  p_value <- mean(abs(results_underH0_diff) >= abs(boot_diff))
  pvals_1cp[paste0(stat_name), "Pval"] <- round(p_value, 3)
}

##Add outcomes to dataframe (function to establish dataframe as desired)
create_df <- function(method_name, boot_acc_index, boot_ppv_index, boot_npv_index, boot_sen_index, boot_spec_index,boot_tp_index,boot_fp_index,boot_tn_index,boot_fn_index) {
  data.frame(
    method = method_name,
    accuracy = round(boot_results$t0[boot_acc_index], 3),
    acc_ci_lower = round(quantile(boot_results$t[, boot_acc_index], c(0.025, 0.975), na.rm=T)[1], 3),
    acc_ci_upper = round(quantile(boot_results$t[, boot_acc_index], c(0.025, 0.975), na.rm=T)[2], 3),
    PPV = round(boot_results$t0[boot_ppv_index], 3),
    ppv_ci_lower = round(quantile(boot_results$t[, boot_ppv_index], c(0.025, 0.975), na.rm=T)[1], 3),
    ppv_ci_upper = round(quantile(boot_results$t[, boot_ppv_index], c(0.025, 0.975), na.rm=T)[2], 3),
    NPV = round(boot_results$t0[boot_npv_index], 3),
    npv_ci_lower = round(quantile(boot_results$t[, boot_npv_index], c(0.025, 0.975), na.rm=T)[1], 3),
    npv_ci_upper = round(quantile(boot_results$t[, boot_npv_index], c(0.025, 0.975), na.rm=T)[2], 3),
    Sensitivity =round(boot_results$t0[boot_sen_index], 3),
    sen_ci_lower = round(quantile(boot_results$t[, boot_sen_index], c(0.025, 0.975), na.rm=T)[1], 3),
    sen_ci_upper = round(quantile(boot_results$t[, boot_sen_index], c(0.025, 0.975), na.rm=T)[2], 3),
    Specificity = round(boot_results$t0[boot_spec_index], 3),
    spec_ci_lower = round(quantile(boot_results$t[, boot_spec_index], c(0.025, 0.975), na.rm=T)[1], 3),
    spec_ci_upper = round(quantile(boot_results$t[, boot_spec_index], c(0.025, 0.975), na.rm=T)[2], 3),
    TP = round(boot_results$t0[boot_tp_index], 0),
    FP = round(boot_results$t0[boot_fp_index], 0),
    TN = round(boot_results$t0[boot_tn_index], 0),
    FN = round(boot_results$t0[boot_fn_index], 0),
    intermediate_n_percentage = NA,
    intermediate_n_percentage_low = NA,
    intermediate_n_percentage_high = NA,
    stringsAsFactors = FALSE,
    row.names = "1 Cutpoint"
  )
}

results_1cp_2 <- create_df(method_name = "Plasma p-tau217/AB42",boot_acc_index = 1,boot_ppv_index = 3,boot_npv_index = 5, boot_sen_index=11, boot_spec_index=13,boot_tp_index = 16, boot_fp_index=17, boot_tn_index=18, boot_fn_index=19)

results_1cp_3 <- create_df(method_name = "CSF AB42/40",boot_acc_index = 2,boot_ppv_index = 4,boot_npv_index = 6, boot_sen_index=12, boot_spec_index=14,boot_tp_index = 20, boot_fp_index=21, boot_tn_index=22, boot_fn_index=23)

merged_results_1cp <- rbind(results_1cp_2, results_1cp_3)

#Step 2: establish the intermediate zone

df <- df %>%
  mutate(greyzone_ptau217ab42 = case_when(
    ptau217ab42_neg == 0 ~ 1,  # sens95 equals 0
    ptau217ab42_pos == 1 ~ 3,  # spec95 equals 1
    TRUE ~ 2                     # Intermediate values
  ))

df <- df %>%
  mutate(greyzone_ab4240 = case_when(
    ab4240_pos == 0 ~ 1,  # sens95 equals 0 # so when they're negative 0.072
    ab4240_pos2 == 1 ~ 3,  # spec95 equals 1 #so when they're positive even 0.058
    TRUE ~ 2                     # Intermediate values
  ))

#table(df$greyzone_ab4240)

###Function to bootstrap %intermediate
f_greyzone <- function(data, indices){
  d <- data[indices, ]
  
  test_bio <- c("PL_217_42", "csf_ab4240")
  pred_pos <- c("ptau217ab42_pos", "ab4240_pos")
  pred_neg <- c("ptau217ab42_neg", "ab4240_pos2")
  
  for (i in seq_along(test_bio)) {
    greyzone_col <- paste0("greyzone_", test_bio[i])
    neg_col <- pred_neg[i]
    pos_col <- pred_pos[i]
    
    d <- d %>%
      mutate(!!greyzone_col := case_when(
        !!sym(neg_col) == 0 ~ 1,  # sens95 equals 0
        !!sym(pos_col) == 1 ~ 3,  # spec95 equals 1
        TRUE ~ 2
      ))  
  }
  
  int_n_ptau217ab42 <- length(which(d$greyzone_PL_217_42 ==2))
  int_perc_ptau217ab42 <- round((length(which(d$greyzone_PL_217_42 == 2)) / nrow(d)) * 100, 3)
  
  int_n_csf <- length(which(d$greyzone_ab4240 ==2))
  int_perc_csf <- round((length(which(d$greyzone_ab4240 == 2)) / nrow(d)) * 100, 3)
  
  #DIFFERENCES BETWEEN ASSAYS
  diff_perc_ptau217ab42_csf <- int_perc_ptau217ab42 - int_perc_csf
  
  return(c(int_perc_ptau217ab42,int_perc_csf, diff_perc_ptau217ab42_csf))
}

set.seed(12345)
boot_results_greyzone <- boot(data = df, statistic = f_greyzone, R = 2000)

##Calculate pvalue %intermediate differences
stat_indices <- list("Int% pval p-tau217/AB42 vs.CSF" = 3)

pvals_intermediate <- data.frame(
  Pval = numeric(length(stat_indices)),
  row.names = c("Int% pval p-tau217/AB42 vs.CSF"))

bootstrap_replicates_grey <- boot_results_greyzone$t

for (stat_name in names(stat_indices)) {
  index <- stat_indices[[stat_name]]
  boot_diff <- boot_results_greyzone$t0[index]
  results_underH0_diff <- bootstrap_replicates_grey[, index] - mean(bootstrap_replicates_grey[, index])
  p_value <- mean(abs(results_underH0_diff) >= abs(boot_diff))
  pvals_intermediate[paste0(stat_name), "Pval"] <- round(p_value, 3)
}

#Step 3: Two cutoff approach

f_comp_stats_2cp <- function(data, indices) {
  d <- as.data.frame(data[indices,])
  
  
  compute_metrics <- function(d,greyzone, true, pred) {
    
    dx <- d %>% filter(!!sym(greyzone) != 2)
    
    v_tp <- sum(dx[[true]] == 1 & dx[[pred]] == 1)
    v_fp <- sum(dx[[true]] == 0 & dx[[pred]] == 1)
    v_tn <- sum(dx[[true]] == 0 & dx[[pred]] == 0)
    v_fn <- sum(dx[[true]] == 1 & dx[[pred]] == 0)
    
    sens <- v_tp / (v_tp + v_fn)
    spec <- v_tn / (v_tn + v_fp)
    acc <- (v_tp + v_tn) / (v_tp + v_tn + v_fn + v_fp)
    ppv <- cutpointr::ppv(tp = v_tp, fp = v_fp, tn = v_tn, fn = v_fn)
    npv <- cutpointr::npv(tp = v_tp, fp = v_fp, tn = v_tn, fn = v_fn)
    
    return(c(acc, ppv, npv, sens, spec, v_tp, v_fp, v_tn, v_fn))
  }
  
  greyzones <- c("greyzone_ptau217ab42","greyzone_ab4240")
  test_columns <- c("ptau217ab42_pos", "ab4240_pos")
  true_label <- "petstat"
  
  results <- matrix(nrow = length(test_columns), ncol =9)
  colnames(results) <- c("Accuracy", "PPV", "NPV", "Sensitivity", "Specificity", "TP", "FP", "TN", "FN")
  rownames(results) <- c("PL_217_42", "csf_4240")
  
  for (i in seq_along(test_columns)) {
    results[i, ] <- round(compute_metrics(d, greyzone = greyzones[i], true = true_label, pred = test_columns[i]),3)
  }
  
  #P-tau217/AB42
  acc1 <- results[1,1]
  ppv1 <- results[1,2]
  npv1 <- results[1,3]
  sens1 <- results[1,4]
  spec1 <- results[1,5]
  tp1 <- results[1,6]
  fp1 <- results[1,7]
  tn1 <- results[1,8]
  fn1 <- results[1,9]
  
  #CSF
  acc2 <- results[2,1]
  ppv2 <- results[2,2]
  npv2 <- results[2,3]
  sens2 <- results[2,4]
  spec2 <- results[2,5]
  tp2 <- results[2,6]
  fp2 <- results[2,7]
  tn2 <- results[2,8]
  fn2 <- results[2,9]
  
  #p-tau217 vs. 217/ab42
  diff_acc <- acc1 - acc2
  diff_ppv <- ppv1 - ppv2
  diff_npv <- npv1 - npv2
  diff_sens <- sens1 - sens2
  
  
  return(c(acc1, acc2, ppv1, ppv2, npv1, npv2,#6
           diff_acc, diff_ppv, diff_npv, diff_sens,#10
           sens1, sens2, spec1, spec2, diff_sens, #15
           tp1, fp1, tn1, fn1, tp2, fp2, tn2, fn2)) #23
} 

set.seed(12345)
boot_results_2cp <- boot(data = df, statistic = f_comp_stats_2cp, R = 2000)

##Calculate pvalues two cutoffs
stat_indices <- list(
  "Accuracy 217_AB42 vs. CSF" = 7,
  "PPV 217_AB42 vs. CSF" = 8,
  "NPV 217_AB42 vs. CSF" = 9)

pvals_2cp <- data.frame(
  Pval = numeric(length(stat_indices)),
  row.names = c("Accuracy 217_AB42 vs. CSF","PPV 217_AB42 vs. CSF","NPV 217_AB42 vs. CSF"))

bootstrap_replicates_2 <- boot_results_2cp$t
for (stat_name in names(stat_indices)) {
  index <- stat_indices[[stat_name]]
  boot_diff <- boot_results_2cp$t0[index]
  results_underH0_diff <- bootstrap_replicates_2[, index] - mean(bootstrap_replicates_2[, index])
  p_value <- mean(abs(results_underH0_diff) >= abs(boot_diff))
  pvals_2cp[paste0(stat_name), "Pval"] <- round(p_value, 3)
}

##Add results to dataframe
create_df_2 <- function(method_name, boot_acc_index, boot_ppv_index, boot_npv_index,boot_grey_index,boot_sen_index, boot_spec_index,boot_tp_index,boot_fp_index,boot_tn_index,boot_fn_index) {
  data.frame(
    method = method_name,
    accuracy = round(boot_results_2cp$t0[boot_acc_index], 3),
    acc_ci_lower = round(quantile(boot_results_2cp$t[, boot_acc_index], c(0.025, 0.975), na.rm=T)[1], 3),
    acc_ci_upper = round(quantile(boot_results_2cp$t[, boot_acc_index], c(0.025, 0.975), na.rm=T)[2], 3),
    PPV = round(boot_results_2cp$t0[boot_ppv_index], 3),
    ppv_ci_lower = round(quantile(boot_results_2cp$t[, boot_ppv_index], c(0.025, 0.975), na.rm=T)[1], 3),
    ppv_ci_upper = round(quantile(boot_results_2cp$t[, boot_ppv_index], c(0.025, 0.975), na.rm=T)[2], 3),
    NPV = round(boot_results_2cp$t0[boot_npv_index], 3),
    npv_ci_lower = round(quantile(boot_results_2cp$t[, boot_npv_index], c(0.025, 0.975), na.rm=T)[1], 3),
    npv_ci_upper = round(quantile(boot_results_2cp$t[, boot_npv_index], c(0.025, 0.975), na.rm=T)[2], 3),
    Sensitivity =round(boot_results_2cp$t0[boot_sen_index], 3),
    sen_ci_lower = round(quantile(boot_results_2cp$t[, boot_sen_index], c(0.025, 0.975), na.rm=T)[1], 3),
    sen_ci_upper = round(quantile(boot_results_2cp$t[, boot_sen_index], c(0.025, 0.975), na.rm=T)[2], 3),
    Specificity = round(boot_results_2cp$t0[boot_spec_index], 3),
    spec_ci_lower = round(quantile(boot_results_2cp$t[, boot_spec_index], c(0.025, 0.975), na.rm=T)[1], 3),
    spec_ci_upper = round(quantile(boot_results_2cp$t[, boot_spec_index], c(0.025, 0.975), na.rm=T)[2], 3),
    TP = round(boot_results_2cp$t0[boot_tp_index], 0),
    FP = round(boot_results_2cp$t0[boot_fp_index], 0),
    TN = round(boot_results_2cp$t0[boot_tn_index], 0),
    FN = round(boot_results_2cp$t0[boot_fn_index], 0),
    intermediate_n_percentage = round(boot_results_greyzone$t0[boot_grey_index],3),
    intermediate_n_percentage_low = round(quantile(boot_results_greyzone$t[, boot_grey_index], c(0.025, 0.975), na.rm=T)[1], 3),
    intermediate_n_percentage_high = round(quantile(boot_results_greyzone$t[, boot_grey_index], c(0.025, 0.975), na.rm=T)[2], 3),
    stringsAsFactors = FALSE,
    row.names = "2 Cutpoints"
  )
}

results_2cp_2 <- create_df_2(method_name = "Plasma p-tau217/AB42",boot_acc_index = 1,boot_ppv_index = 3,boot_npv_index = 5, boot_grey_index = 1, boot_sen_index=11, boot_spec_index=13,boot_tp_index = 16, boot_fp_index=17, boot_tn_index=18, boot_fn_index=19)

results_2cp_3 <- create_df_2(method_name = "CSF AB42/40",boot_acc_index = 2,boot_ppv_index = 4,boot_npv_index = 6, boot_grey_index = 2, boot_sen_index=12, boot_spec_index=14,boot_tp_index = 20, boot_fp_index=21, boot_tn_index=22, boot_fn_index=23)

merged_results_2cp <- rbind(results_2cp_2, results_2cp_3)

#Step 4: Bind all datasets together
merged_comps_bf <- rbind(merged_results_1cp, merged_results_2cp)
merged_comps_bf$Cutpoints <- c("1 Cutpoint","1 Cutpoint","2 Cutpoints","2 Cutpoints")
openxlsx::write.xlsx(merged_comps_bf,file="~/Results.xlsx", rowNames =T)

pvalues_all <- rbind(
  pvals_1cp,
  pvals_intermediate,
  pvals_2cp
)
openxlsx::write.xlsx(pvalues_all,file="~/Results_pvals.xlsx", rowNames =T)


#Step 5: Create dataframe for manuscript tables
table_df <- data.frame(
Measure = merged_comps_bf$method,
Accuracy = sprintf("%.2f (%.2f-%.2f)", merged_comps_bf$accuracy, merged_comps_bf$acc_ci_lower, merged_comps_bf$acc_ci_upper),
PPV = sprintf("%.2f (%.2f-%.2f)", merged_comps_bf$PPV, merged_comps_bf$ppv_ci_lower, merged_comps_bf$ppv_ci_upper),
NPV = sprintf("%.2f (%.2f-%.2f)", merged_comps_bf$NPV, merged_comps_bf$npv_ci_lower, merged_comps_bf$npv_ci_upper),
Gre= sprintf("%.2f (%.2f-%.2f)", merged_comps_bf$intermediate_n_percentage, merged_comps_bf$intermediate_n_percentage_low, merged_comps_bf$intermediate_n_percentage_high),
Sensitivity = sprintf("%.2f (%.2f-%.2f)", merged_comps_bf$Sensitivity, merged_comps_bf$sen_ci_lower, merged_comps_bf$sen_ci_upper),
Specificity =sprintf("%.2f (%.2f-%.2f)", merged_comps_bf$Specificity, merged_comps_bf$spec_ci_lower, merged_comps_bf$spec_ci_upper), 
TP =sprintf("%.2f", merged_comps_bf$TP),
FP =sprintf("%.2f", merged_comps_bf$FP),
TN =sprintf("%.2f", merged_comps_bf$TN), 
FN =sprintf("%.2f", merged_comps_bf$FN))

openxlsx::write.xlsx(table_df,file="~/Results_table.xlsx", rowNames =T)

```

### Metric figures VR (BFMC)

```{r metric fic BFMC}

###1 Cutoff
merged_comps_bf <- read_xlsx("~/Results.xlsx")
merged_comps_bf <- merged_comps_bf[,2:24]

###Assemble plot data in way required for plots
plot_acc <- cbind(merged_comps_bf[0:2, 1], merged_comps_bf[0:2,2:4])
colnames(plot_acc) <- c("Method", "Measure1", "ci_low", "ci_high")
plot_acc$Measure <- c("Accuracy", "Accuracy")

plot_ppv <- cbind(merged_comps_bf[0:2, 1], merged_comps_bf[0:2,5:7])
colnames(plot_ppv) <- c("Method", "Measure1", "ci_low", "ci_high")
plot_ppv$Measure <- c("PPV", "PPV")

plot_npv <- cbind(merged_comps_bf[0:2, 1], merged_comps_bf[0:2,8:10])
colnames(plot_npv) <- c("Method", "Measure1", "ci_low", "ci_high")
plot_npv$Measure <- c("NPV", "NPV")

plotdata <- rbind(plot_acc, plot_ppv, plot_npv)
plotdata1 <- plotdata
plotdata1$Method2 <- as.factor(c("2", "1"))

group_order <- c("NPV", "PPV", "Accuracy")
tick_positions <- seq(70, 100, by = 10)

###Forest plot Acc, PPV, NPV
ggplot(data=plotdata1, aes(y = factor(Measure, levels=group_order), x = Measure1 * 100, color=Method2, fill=Method2))+
  geom_vline(xintercept = tick_positions, color = "grey80", linewidth = 0.5, alpha=0.4) +
  geom_errorbar(aes(xmin = ci_low * 100, xmax = ci_high * 100),
                width = 0, linewidth = 0.75, position = position_dodge(width = 0.6)) +
  geom_point(position = position_dodge(width = 0.6), size = 1.75, stroke = 0.7)+
  scale_x_continuous(limits=c(70,110),breaks = seq(70,110, by=10),expand =c(0,0))+
  labs(x = "Percentage", y = "") +
  geom_text(aes(label = sprintf("%.f (%.f-%.f)", Measure1 * 100, ci_low * 100, ci_high * 100), group=Method2, x=106),
            position = position_dodge(width = 0.6), size = 2) +
  scale_color_manual(values=c("#295dbf", "#c52851"), guide="none")+
  scale_fill_manual(values=c("#295dbf", "#c52851"), guide="none")+
  theme_classic()+ 
  theme(axis.text.x = element_text(size = 7,color="grey30"),
        axis.text.y = element_text(size = 7, color="black"),
        axis.title.x = element_text(size = 7,color="black"),
        axis.ticks.y = element_blank(),
        legend.text = element_text(size = 6,color="black"),  
        legend.title = element_blank(), 
        legend.position = "bottom")

###2 Cutoffs
merged_comps_bf <- read_xlsx("~/Results.xlsx")
merged_comps_bf <- merged_comps_bf[,2:24]

###Assemble plot data in way required for plots
plot_acc <- cbind(merged_comps_bf[3:4, 1], merged_comps_bf[3:4,2:4])
colnames(plot_acc) <- c("Method", "Measure1", "ci_low", "ci_high")
plot_acc$Measure <- c("Accuracy", "Accuracy")

plot_ppv <- cbind(merged_comps_bf[3:4, 1], merged_comps_bf[3:4,5:7])
colnames(plot_ppv) <- c("Method", "Measure1", "ci_low", "ci_high")
plot_ppv$Measure <- c("PPV", "PPV")

plot_npv <- cbind(merged_comps_bf[3:4, 1], merged_comps_bf[3:4,8:10])
colnames(plot_npv) <- c("Method", "Measure1", "ci_low", "ci_high")
plot_npv$Measure <- c("NPV", "NPV")

plotdata <- rbind(plot_acc, plot_ppv, plot_npv)
plotdata1 <- plotdata
plotdata1$Method2 <- as.factor(c("2", "1"))

group_order <- c("NPV", "PPV", "Accuracy")
tick_positions <- seq(70, 100, by = 10)

###Forest plot Acc, PPV, NPV
ggplot(data=plotdata1, aes(y = factor(Measure, levels=group_order), x = Measure1 * 100, color=Method2, fill=Method2))+
  geom_vline(xintercept = tick_positions, color = "grey80", linewidth = 0.5, alpha=0.4) +
  geom_errorbar(aes(xmin = ci_low * 100, xmax = ci_high * 100),
                width = 0, linewidth = 0.75, position = position_dodge(width = 0.6)) +
  geom_point(position = position_dodge(width = 0.6), size = 1.75, stroke = 0.7)+
  scale_x_continuous(limits=c(70,110),breaks = seq(70,110, by=10),expand =c(0,0))+
  labs(x = "Percentage", y = "") +
  geom_text(aes(label = sprintf("%.f (%.f-%.f)", Measure1 * 100, ci_low * 100, ci_high * 100), group=Method2, x=106),
            position = position_dodge(width = 0.6), size = 2) +
  scale_color_manual(values=c("#295dbf", "#c52851"), guide="none")+
  scale_fill_manual(values=c("#295dbf", "#c52851"), guide="none")+
  theme_classic()+ 
  theme(axis.text.x = element_text(size = 7,color="grey30"),
        axis.text.y = element_text(size = 7, color="black"),
        axis.title.x = element_text(size = 7,color="black"),
        axis.ticks.y = element_blank(),
        legend.text = element_text(size = 6,color="black"),  
        legend.title = element_blank(), 
        legend.position = "bottom")

###Intermediate plot
plot_grey <- cbind(merged_comps_bf[3:4, 1], merged_comps_bf[3:4, 21:23])
colnames(plot_grey) <- c("Method", "Measure1", "ci_low", "ci_high")
group_order <- c("Plasma p-tau217/AB42", "CSF AB42/40")

ggplot(data=plot_grey, aes(x=factor(Method,levels = c("Plasma p-tau217/AB42", "CSF AB42/40")),y=Measure1, fill=factor(Method, levels = c("Plasma p-tau217/AB42", "CSF AB42/40"))))+
  geom_bar(color="black",stat = "identity", alpha=0.8, width=0.6,  position = position_dodge(width = 0.1),)+
  geom_errorbar(aes(x=factor(Method,level = c("Plasma p-tau217/AB42", "CSF AB42/40")), ymax = ci_high, ymin = ci_low),width=0.2, size =0.5,position=position_dodge(0.1),  color="black")+
  scale_y_continuous(limits=c(0,40),breaks = seq(0,40, by=10),expand =c(0,0))+
  geom_text(aes(label = sprintf("%.1f", Measure1)), position = position_dodge(width=0.75), vjust=-3, size = 2) +
  scale_fill_manual(values = c("#c52851", "#295dbf"), guide="none") +
  labs(title = element_blank(),x = "",y = "Intermediate values (%)") +
  theme_classic()+
  theme(axis.text.y = element_text(size=6),
        axis.text.x = element_text(size=6),
        axis.title.x = element_text(size=6),
        axis.title.y= element_text(size=6),
        panel.border = element_rect(linewidth = 0.5, fill = NA, color=NA))  

```

## 1B. Centiloids 24 outcome

------------------------------------------------------------------------

### Boxplots CL24 (BFMC)

```{r boxplots CL24 BFMC}
df$petstat <- as.factor(ifelse(df$CL_fnc_ber_com_composite >= 24, 1, 0)) 
df <- df %>% drop_na(petstat)

ggplot(df, aes(x = petstat, y = PL_217_42, fill=petstat)) +
  annotate("rect", xmin = -Inf, xmax = Inf, ymin = 0.0037, ymax = 0.0074,
           fill = "grey80", alpha = 0.4) +
  geom_violin(alpha=0.3) +
  geom_hline(yintercept=0.00738, linetype="dashed", color="grey20", alpha=.8, linewidth = .35) +
  geom_hline(yintercept=0.0037, linetype="dashed", color="grey20", alpha = .8, linewidth = .35) +
  geom_quasirandom(alpha = 0.75, size = 1,shape=21, color="black", stroke=0.25) +
  scale_y_continuous(breaks = round(seq(0, 0.1, by = 0.025), 3), limits = c(0, 0.085)) +
  scale_x_discrete(labels=c("0" ="VR-","1" ="VR+")) +
  labs(x = "AD status", y = "Plasma p-tau217/AB42") +
  scale_fill_manual(values = c("#afafaf", "#c52851"), guide = "none") +
  theme_classic() +
  theme(axis.title.x = element_blank(),
        axis.title.y = element_text(size=7),
        axis.text.x = element_text(size=6),
        axis.text.y = element_text(size=6))+
  stat_compare_means(method="t.test", label="p.signif", label.x = 1.5, label.y = 0.04)

##CSF
ggplot(df, aes(x = petstat, y = csf_4240, fill=petstat)) +
  annotate("rect", xmin = -Inf, xmax = Inf, ymin = 0.058, ymax = 0.072,
           fill = "grey80", alpha = 0.4) +
  geom_violin(alpha=0.3) +
  geom_hline(yintercept=0.058, linetype="dashed", color="grey20", alpha=.8, linewidth = .35) +
  geom_hline(yintercept=0.072, linetype="dashed", color="grey20", alpha = .8, linewidth = .35) +
  geom_quasirandom(alpha = 0.75, size = 1,shape=21, color="black", stroke=0.25) +
  scale_x_discrete(labels=c("0" ="VR-","1" ="VR+")) +
  labs(x = "AD status", y = "CSF AB42/40") +
  scale_fill_manual(values = c("#afafaf", "#295dbf"), guide = "none") +
  theme_classic() +
  theme(axis.title.x = element_blank(),
        axis.title.y = element_text(size=7),
        axis.text.x = element_text(size=6),
        axis.text.y = element_text(size=6))+
  stat_compare_means(method="t.test", label="p.signif", label.x = 1.5, label.y = 0.04)

```

### Analyses CL24 AUC (BFMC)

```{r BFMC,AB-PET CL24 outcome}
##AUC differences with DeLong
df$petstat <- as.factor(ifelse(df$CL_fnc_ber_com_composite >= 24, 1, 0)) 

#| echo: false
biomarkers <- c("ptau217","PL_217_42", "csf_4240")
results_delong <- list()
index <- 1

library(pROC)

for (i in seq_along(biomarkers)){
  for (j in seq_along(biomarkers)){ 
    if (i < j) {
      predictor1 <- biomarkers[i]
      predictor2 <- biomarkers[j]
      
      formula1 <- as.formula(paste("petstat~",predictor1, collapse=""))
      formula2 <- as.formula(paste("petstat~",predictor2, collapse=""))
      
      roc_curve1 <- pROC::roc(formula1, data=df, quiet=T)
      roc_curve2 <- pROC::roc(formula2, data=df,quiet=T)
      
      res <- roc.test(roc_curve1, roc_curve2, method = "delong")
      
      long <- data.frame(
        comp = paste(predictor1, predictor2, sep=" vs. "),
        auc1a = round(roc_curve1$auc,3),
        auc2a = round(roc_curve2$auc,3),
        pval = round(res$p.value,3),
        auc1_ci_low = round(ci.auc(roc_curve1)[1],3),
        auc1_ci_high =round(ci.auc(roc_curve1)[3],3),
        auc2_ci_low =round(ci.auc(roc_curve2)[1],3),
        auc2_ci_high = round(ci.auc(roc_curve2)[3],3)
      )
      
      results_delong[[length(results_delong) + 1]] <- long
      index <- index + 1
    }
  }
}

results_delong <- do.call(rbind.data.frame, results_delong)
results_delong$padj <- round(p.adjust(results_delong$pval, method = "fdr"),3)
results_delong$auc_order <- c(results_delong$auc1a[1],results_delong$auc1a[3], results_delong$auc2a[3])
results_delong$auc_order_ci_low <- c(results_delong$auc1_ci_low[1],results_delong$auc1_ci_low[3], results_delong$auc2_ci_low[3])
results_delong$auc_order_ci_high <- c(results_delong$auc1_ci_high[1],results_delong$auc1_ci_high[3], results_delong$auc2_ci_high[3])
openxlsx::write.xlsx(results_delong,
                     file="~/DELONG_VR.xlsx")

##AUC plot
roc_curve2 <- pROC::roc(petstat ~ ptau217, data=df,quiet=T)
auc2 <- auc(roc_curve2)
roc_curve1 <- pROC::roc(petstat ~ PL_217_42, data=df,quiet=T)
auc1 <- auc(roc_curve1)
roc_curve3 <- pROC::roc(petstat ~ csf_4240, data=df,quiet=T)
auc3 <- auc(roc_curve3)

roc_list <- list(roc_curve1, roc_curve2, roc_curve3)

ggroc(roc_list) +
  scale_color_manual(values = c("#c52851", "#4ca481", "#295dbf"), 
                     labels = c("Plasma p-tau217/AB42", "Plasma p-tau217", "CSF AB42/40"), guide="none") +
  labs(title = element_blank(), x = "Specificity", y = "Sensitivity", color = "Assay") +
  scale_x_reverse()+
  scale_y_continuous()+
  geom_abline(slope = 1, intercept = 1, linetype = "dashed") +
  theme_classic()+
  theme(panel.border = element_blank(),
        axis.text.y = element_text(size = 5,color="grey30"),
        axis.text.x = element_text(size = 5,color="grey30"),
        axis.title.x = element_text(size=6,color="black"),
        axis.title.y = element_text(size=6),color="black")+
  annotate("text", x=0.3, y=0.25, 
           label = sprintf("%.2f (%.2f, %.2f)", auc(roc_curve1), ci.auc(roc_curve1)[1], ci.auc(roc_curve1)[3]),
           size = 2, color = "#c52851")+
  annotate("text", x=0.3, y=0.15, 
           label = sprintf("%.2f (%.2f, %.2f)", auc(roc_curve2), ci.auc(roc_curve2)[1], ci.auc(roc_curve2)[3]),
           size = 2, color = "#4ca481")+
  annotate("text", x=0.3, y=0.05, 
           label = sprintf("%.2f (%.2f, %.2f)", auc(roc_curve3), ci.auc(roc_curve3)[1], ci.auc(roc_curve3)[3]),
           size = 2, color = "#295dbf")

```

### Metrics CL24 (BFMC)

```{r metrics CL24 BFMC}
df$petstat <- as.factor(ifelse(df$CL_fnc_ber_com_composite >= 24, 1, 0)) 

df$ptau217ab42_pos <- ifelse(df$PL_217_42 >= 0.00738, 1, 0) 
df$ptau217ab42_neg <- ifelse(df$PL_217_42 <= 0.00370, 0, 1)

df$ab4240_pos <- ifelse(df$csf_4240 <= 0.072, 1, 0)
df$ab4240_pos2 <- ifelse(df$csf_4240 <= 0.058, 1, 0)

##Calculate Accuracy, PPV, NPV and 95% CIs

f_comp_stats <- function(data, indices) {
  d <- as.data.frame(data[indices,])
  
  ##threshold calculation related to d, and then assign binary status based on that threshold
  compute_metrics <- function(true, pred) {
    
    ##threshold calculation and 
    
    v_tp <- sum(true == 1 & pred == 1)
    v_fp <- sum(true == 0 & pred == 1)
    v_tn <- sum(true == 0 & pred == 0)
    v_fn <- sum(true == 1 & pred == 0)
    
    sens <- v_tp / (v_tp + v_fn)
    spec <- v_tn / (v_tn + v_fp)
    acc <- (v_tp + v_tn) / (v_tp + v_tn + v_fn + v_fp)
    ppv <- cutpointr::ppv(tp = v_tp, fp = v_fp, tn = v_tn, fn = v_fn)
    npv <- cutpointr::npv(tp = v_tp, fp = v_fp, tn = v_tn, fn = v_fn)
    
    return(c(acc, ppv, npv, sens, spec, v_tp, v_fp, v_tn, v_fn))#sens#spec
  }
  
  test_columns <- c("ptau217ab42_pos", "ab4240_pos")
  results <- matrix(nrow = length(test_columns), ncol = 9)
  colnames(results) <- c("Accuracy", "PPV", "NPV", "Sensitivity", "Specificity", "TP", "FP", "TN", "FN")
  rownames(results) <- c("PL_217_42", "csf_4240")
  
  for (i in seq_along(test_columns)) {
    results[i, ] <- round(compute_metrics(d$petstat, d[[test_columns[i]]]),3)
  }
  
  #Assign p-tau217/AB42 metrics
  acc1 <- results[1,1]
  ppv1 <- results[1,2]
  npv1 <- results[1,3]
  sens1 <- results[1,4]
  spec1 <- results[1,5]
  tp1 <- results[1,6]
  fp1 <- results[1,7]
  tn1 <- results[1,8]
  fn1 <- results[1,9]
  
  #Assign CSF metrics
  acc2 <- results[2,1]
  ppv2 <- results[2,2]
  npv2 <- results[2,3]
  sens2 <- results[2,4]
  spec2 <- results[2,5]
  tp2 <- results[2,6]
  fp2 <- results[2,7]
  tn2 <- results[2,8]
  fn2 <- results[2,9]
  
  #p-tau217 vs. 217/ab42
  diff_acc <- acc1 - acc2
  diff_ppv <- ppv1 - ppv2
  diff_npv <- npv1 - npv2
  diff_sens <- sens1 - sens2
  
  
  return(c(acc1, acc2, ppv1, ppv2, npv1, npv2,#6
           diff_acc, diff_ppv, diff_npv, diff_sens,#10
           sens1, sens2, spec1, spec2, diff_sens, #15
           tp1, fp1, tn1, fn1, tp2, fp2, tn2, fn2)) #23
}   

set.seed(12345)
boot_results <- boot(data = df, statistic = f_comp_stats, R = 2000)

#Calculate pvalues 1 cutoff
stat_indices <- list(
  "Accuracy 217_AB42 vs. CSF" = 7,
  "PPV 217_AB42 vs. CSF" = 8,
  "NPV 217_AB42 vs. CSF" = 9)

pvals_1cp <- data.frame(
  Pval = numeric(length(stat_indices)),
  row.names = c("Accuracy 217_AB42 vs. CSF","PPV 217_AB42 vs. CSF","NPV 217_AB42 vs. CSF"))

bootstrap_replicates <- boot_results$t
for (stat_name in names(stat_indices)) {
  index <- stat_indices[[stat_name]]
  boot_diff <- boot_results$t0[index]
  results_underH0_diff <- bootstrap_replicates[, index] - mean(bootstrap_replicates[, index])
  p_value <- mean(abs(results_underH0_diff) >= abs(boot_diff))
  pvals_1cp[paste0(stat_name), "Pval"] <- round(p_value, 3)
}

##Add outcomes to dataframe (function to establish dataframe as desired)
create_df <- function(method_name, boot_acc_index, boot_ppv_index, boot_npv_index, boot_sen_index, boot_spec_index,boot_tp_index,boot_fp_index,boot_tn_index,boot_fn_index) {
  data.frame(
    method = method_name,
    accuracy = round(boot_results$t0[boot_acc_index], 3),
    acc_ci_lower = round(quantile(boot_results$t[, boot_acc_index], c(0.025, 0.975), na.rm=T)[1], 3),
    acc_ci_upper = round(quantile(boot_results$t[, boot_acc_index], c(0.025, 0.975), na.rm=T)[2], 3),
    PPV = round(boot_results$t0[boot_ppv_index], 3),
    ppv_ci_lower = round(quantile(boot_results$t[, boot_ppv_index], c(0.025, 0.975), na.rm=T)[1], 3),
    ppv_ci_upper = round(quantile(boot_results$t[, boot_ppv_index], c(0.025, 0.975), na.rm=T)[2], 3),
    NPV = round(boot_results$t0[boot_npv_index], 3),
    npv_ci_lower = round(quantile(boot_results$t[, boot_npv_index], c(0.025, 0.975), na.rm=T)[1], 3),
    npv_ci_upper = round(quantile(boot_results$t[, boot_npv_index], c(0.025, 0.975), na.rm=T)[2], 3),
    Sensitivity =round(boot_results$t0[boot_sen_index], 3),
    sen_ci_lower = round(quantile(boot_results$t[, boot_sen_index], c(0.025, 0.975), na.rm=T)[1], 3),
    sen_ci_upper = round(quantile(boot_results$t[, boot_sen_index], c(0.025, 0.975), na.rm=T)[2], 3),
    Specificity = round(boot_results$t0[boot_spec_index], 3),
    spec_ci_lower = round(quantile(boot_results$t[, boot_spec_index], c(0.025, 0.975), na.rm=T)[1], 3),
    spec_ci_upper = round(quantile(boot_results$t[, boot_spec_index], c(0.025, 0.975), na.rm=T)[2], 3),
    TP = round(boot_results$t0[boot_tp_index], 0),
    FP = round(boot_results$t0[boot_fp_index], 0),
    TN = round(boot_results$t0[boot_tn_index], 0),
    FN = round(boot_results$t0[boot_fn_index], 0),
    intermediate_n_percentage = NA,
    intermediate_n_percentage_low = NA,
    intermediate_n_percentage_high = NA,
    stringsAsFactors = FALSE,
    row.names = "1 Cutpoint"
  )
}

results_1cp_2 <- create_df(method_name = "Plasma p-tau217/AB42",boot_acc_index = 1,boot_ppv_index = 3,boot_npv_index = 5, boot_sen_index=11, boot_spec_index=13,boot_tp_index = 16, boot_fp_index=17, boot_tn_index=18, boot_fn_index=19)

results_1cp_3 <- create_df(method_name = "CSF AB42/40",boot_acc_index = 2,boot_ppv_index = 4,boot_npv_index = 6, boot_sen_index=12, boot_spec_index=14,boot_tp_index = 20, boot_fp_index=21, boot_tn_index=22, boot_fn_index=23)

merged_results_1cp <- rbind(results_1cp_2, results_1cp_3)

#Step 2: establish the intermediate zone

df <- df %>%
  mutate(greyzone_ptau217ab42 = case_when(
    ptau217ab42_neg == 0 ~ 1,  # sens95 equals 0
    ptau217ab42_pos == 1 ~ 3,  # spec95 equals 1
    TRUE ~ 2                     # Intermediate values
  ))

df <- df %>%
  mutate(greyzone_ab4240 = case_when(
    ab4240_pos == 0 ~ 1,  # sens95 equals 0 # so when they're negative 0.072
    ab4240_pos2 == 1 ~ 3,  # spec95 equals 1 #so when they're positive even 0.058
    TRUE ~ 2                     # Intermediate values
  ))

table(df$greyzone_ab4240)

###Function to bootstrap %intermediate
f_greyzone <- function(data, indices){
  d <- data[indices, ]
  
  test_bio <- c("PL_217_42", "csf_ab4240")
  pred_pos <- c("ptau217ab42_pos", "ab4240_pos")
  pred_neg <- c("ptau217ab42_neg", "ab4240_pos2")
  
  for (i in seq_along(test_bio)) {
    greyzone_col <- paste0("greyzone_", test_bio[i])
    neg_col <- pred_neg[i]
    pos_col <- pred_pos[i]
    
    d <- d %>%
      mutate(!!greyzone_col := case_when(
        !!sym(neg_col) == 0 ~ 1,  # sens95 equals 0
        !!sym(pos_col) == 1 ~ 3,  # spec95 equals 1
        TRUE ~ 2
      ))  
  }
  
  int_n_ptau217ab42 <- length(which(d$greyzone_PL_217_42 ==2))
  int_perc_ptau217ab42 <- round((length(which(d$greyzone_PL_217_42 == 2)) / nrow(d)) * 100, 3)
  
  int_n_csf <- length(which(d$greyzone_ab4240 ==2))
  int_perc_csf <- round((length(which(d$greyzone_ab4240 == 2)) / nrow(d)) * 100, 3)
  
  #DIFFERENCES BETWEEN ASSAYS
  diff_perc_ptau217ab42_csf <- int_perc_ptau217ab42 - int_perc_csf
  
  return(c(int_perc_ptau217ab42,int_perc_csf, diff_perc_ptau217ab42_csf))
}

set.seed(12345)
boot_results_greyzone <- boot(data = df, statistic = f_greyzone, R = 2000)

##Calculate pvalue %intermediate differences
stat_indices <- list("Int% pval p-tau217/AB42 vs.CSF" = 3)

pvals_intermediate <- data.frame(
  Pval = numeric(length(stat_indices)),
  row.names = c("Int% pval p-tau217/AB42 vs.CSF"))

bootstrap_replicates_grey <- boot_results_greyzone$t

for (stat_name in names(stat_indices)) {
  index <- stat_indices[[stat_name]]
  boot_diff <- boot_results_greyzone$t0[index]
  results_underH0_diff <- bootstrap_replicates_grey[, index] - mean(bootstrap_replicates_grey[, index])
  p_value <- mean(abs(results_underH0_diff) >= abs(boot_diff))
  pvals_intermediate[paste0(stat_name), "Pval"] <- round(p_value, 3)
}

#Step 3: Two cutoff approach

f_comp_stats_2cp <- function(data, indices) {
  d <- as.data.frame(data[indices,])
  
  
  compute_metrics <- function(d,greyzone, true, pred) {
    
    dx <- d %>% filter(!!sym(greyzone) != 2)
    
    v_tp <- sum(dx[[true]] == 1 & dx[[pred]] == 1)
    v_fp <- sum(dx[[true]] == 0 & dx[[pred]] == 1)
    v_tn <- sum(dx[[true]] == 0 & dx[[pred]] == 0)
    v_fn <- sum(dx[[true]] == 1 & dx[[pred]] == 0)
    
    sens <- v_tp / (v_tp + v_fn)
    spec <- v_tn / (v_tn + v_fp)
    acc <- (v_tp + v_tn) / (v_tp + v_tn + v_fn + v_fp)
    ppv <- cutpointr::ppv(tp = v_tp, fp = v_fp, tn = v_tn, fn = v_fn)
    npv <- cutpointr::npv(tp = v_tp, fp = v_fp, tn = v_tn, fn = v_fn)
    
    return(c(acc, ppv, npv, sens, spec, v_tp, v_fp, v_tn, v_fn))#sens#spec
  }
  
  greyzones <- c("greyzone_ptau217ab42","greyzone_ab4240")
  test_columns <- c("ptau217ab42_pos", "ab4240_pos")
  true_label <- "petstat"
  
  results <- matrix(nrow = length(test_columns), ncol =9)
  colnames(results) <- c("Accuracy", "PPV", "NPV", "Sensitivity", "Specificity", "TP", "FP", "TN", "FN")
  rownames(results) <- c("PL_217_42", "csf_4240")
  
  for (i in seq_along(test_columns)) {
    results[i, ] <- round(compute_metrics(d, greyzone = greyzones[i], true = true_label, pred = test_columns[i]),3)
  }
  
  #P-tau217/AB42
  acc1 <- results[1,1]
  ppv1 <- results[1,2]
  npv1 <- results[1,3]
  sens1 <- results[1,4]
  spec1 <- results[1,5]
  tp1 <- results[1,6]
  fp1 <- results[1,7]
  tn1 <- results[1,8]
  fn1 <- results[1,9]
  
  #CSF
  acc2 <- results[2,1]
  ppv2 <- results[2,2]
  npv2 <- results[2,3]
  sens2 <- results[2,4]
  spec2 <- results[2,5]
  tp2 <- results[2,6]
  fp2 <- results[2,7]
  tn2 <- results[2,8]
  fn2 <- results[2,9]
  
  #p-tau217 vs. 217/ab42
  diff_acc <- acc1 - acc2
  diff_ppv <- ppv1 - ppv2
  diff_npv <- npv1 - npv2
  diff_sens <- sens1 - sens2
  
  
  return(c(acc1, acc2, ppv1, ppv2, npv1, npv2,#6
           diff_acc, diff_ppv, diff_npv, diff_sens,#10
           sens1, sens2, spec1, spec2, diff_sens, #15
           tp1, fp1, tn1, fn1, tp2, fp2, tn2, fn2)) #23
} 

set.seed(12345)
boot_results_2cp <- boot(data = df, statistic = f_comp_stats_2cp, R = 2000)

##Calculate pvalues two cutoffs
stat_indices <- list(
  "Accuracy 217_AB42 vs. CSF" = 7,
  "PPV 217_AB42 vs. CSF" = 8,
  "NPV 217_AB42 vs. CSF" = 9)

pvals_2cp <- data.frame(
  Pval = numeric(length(stat_indices)),
  row.names = c("Accuracy 217_AB42 vs. CSF","PPV 217_AB42 vs. CSF","NPV 217_AB42 vs. CSF"))

bootstrap_replicates_2 <- boot_results_2cp$t
for (stat_name in names(stat_indices)) {
  index <- stat_indices[[stat_name]]
  boot_diff <- boot_results_2cp$t0[index]
  results_underH0_diff <- bootstrap_replicates_2[, index] - mean(bootstrap_replicates_2[, index])
  p_value <- mean(abs(results_underH0_diff) >= abs(boot_diff))
  pvals_2cp[paste0(stat_name), "Pval"] <- round(p_value, 3)
}

##Add results to dataframe
create_df_2 <- function(method_name, boot_acc_index, boot_ppv_index, boot_npv_index,boot_grey_index,boot_sen_index, boot_spec_index,boot_tp_index,boot_fp_index,boot_tn_index,boot_fn_index) {
  data.frame(
    method = method_name,
    accuracy = round(boot_results_2cp$t0[boot_acc_index], 3),
    acc_ci_lower = round(quantile(boot_results_2cp$t[, boot_acc_index], c(0.025, 0.975), na.rm=T)[1], 3),
    acc_ci_upper = round(quantile(boot_results_2cp$t[, boot_acc_index], c(0.025, 0.975), na.rm=T)[2], 3),
    PPV = round(boot_results_2cp$t0[boot_ppv_index], 3),
    ppv_ci_lower = round(quantile(boot_results_2cp$t[, boot_ppv_index], c(0.025, 0.975), na.rm=T)[1], 3),
    ppv_ci_upper = round(quantile(boot_results_2cp$t[, boot_ppv_index], c(0.025, 0.975), na.rm=T)[2], 3),
    NPV = round(boot_results_2cp$t0[boot_npv_index], 3),
    npv_ci_lower = round(quantile(boot_results_2cp$t[, boot_npv_index], c(0.025, 0.975), na.rm=T)[1], 3),
    npv_ci_upper = round(quantile(boot_results_2cp$t[, boot_npv_index], c(0.025, 0.975), na.rm=T)[2], 3),
    Sensitivity =round(boot_results_2cp$t0[boot_sen_index], 3),
    sen_ci_lower = round(quantile(boot_results_2cp$t[, boot_sen_index], c(0.025, 0.975), na.rm=T)[1], 3),
    sen_ci_upper = round(quantile(boot_results_2cp$t[, boot_sen_index], c(0.025, 0.975), na.rm=T)[2], 3),
    Specificity = round(boot_results_2cp$t0[boot_spec_index], 3),
    spec_ci_lower = round(quantile(boot_results_2cp$t[, boot_spec_index], c(0.025, 0.975), na.rm=T)[1], 3),
    spec_ci_upper = round(quantile(boot_results_2cp$t[, boot_spec_index], c(0.025, 0.975), na.rm=T)[2], 3),
    TP = round(boot_results_2cp$t0[boot_tp_index], 0),
    FP = round(boot_results_2cp$t0[boot_fp_index], 0),
    TN = round(boot_results_2cp$t0[boot_tn_index], 0),
    FN = round(boot_results_2cp$t0[boot_fn_index], 0),
    intermediate_n_percentage = round(boot_results_greyzone$t0[boot_grey_index],3),
    intermediate_n_percentage_low = round(quantile(boot_results_greyzone$t[, boot_grey_index], c(0.025, 0.975), na.rm=T)[1], 3),
    intermediate_n_percentage_high = round(quantile(boot_results_greyzone$t[, boot_grey_index], c(0.025, 0.975), na.rm=T)[2], 3),
    stringsAsFactors = FALSE,
    row.names = "2 Cutpoints"
  )
}

results_2cp_2 <- create_df_2(method_name = "Plasma p-tau217/AB42",boot_acc_index = 1,boot_ppv_index = 3,boot_npv_index = 5, boot_grey_index = 1, boot_sen_index=11, boot_spec_index=13,boot_tp_index = 16, boot_fp_index=17, boot_tn_index=18, boot_fn_index=19)

results_2cp_3 <- create_df_2(method_name = "CSF AB42/40",boot_acc_index = 2,boot_ppv_index = 4,boot_npv_index = 6, boot_grey_index = 2, boot_sen_index=12, boot_spec_index=14,boot_tp_index = 20, boot_fp_index=21, boot_tn_index=22, boot_fn_index=23)

merged_results_2cp <- rbind(results_2cp_2, results_2cp_3)

#Step 4: Bind all datasets together
merged_comps_bf <- rbind(merged_results_1cp, merged_results_2cp)
merged_comps_bf$Cutpoints <- c("1 Cutpoint","1 Cutpoint","2 Cutpoints","2 Cutpoints")
openxlsx::write.xlsx(merged_comps_bf,file="~/Results.xlsx", rowNames =T)

pvalues_all <- rbind(
  pvals_1cp,
  pvals_intermediate,
  pvals_2cp
)
openxlsx::write.xlsx(pvalues_all,file="~/Results_pvals.xlsx", rowNames =T)


#Step 5: Create dataframe for manuscript tables
table_df <- data.frame(
Measure = merged_comps_bf$method,
Accuracy = sprintf("%.2f (%.2f-%.2f)", merged_comps_bf$accuracy, merged_comps_bf$acc_ci_lower, merged_comps_bf$acc_ci_upper),
PPV = sprintf("%.2f (%.2f-%.2f)", merged_comps_bf$PPV, merged_comps_bf$ppv_ci_lower, merged_comps_bf$ppv_ci_upper),
NPV = sprintf("%.2f (%.2f-%.2f)", merged_comps_bf$NPV, merged_comps_bf$npv_ci_lower, merged_comps_bf$npv_ci_upper),
Gre= sprintf("%.2f (%.2f-%.2f)", merged_comps_bf$intermediate_n_percentage, merged_comps_bf$intermediate_n_percentage_low, merged_comps_bf$intermediate_n_percentage_high),
Sensitivity = sprintf("%.2f (%.2f-%.2f)", merged_comps_bf$Sensitivity, merged_comps_bf$sen_ci_lower, merged_comps_bf$sen_ci_upper),
Specificity =sprintf("%.2f (%.2f-%.2f)", merged_comps_bf$Specificity, merged_comps_bf$spec_ci_lower, merged_comps_bf$spec_ci_upper), 
TP =sprintf("%.2f", merged_comps_bf$TP),
FP =sprintf("%.2f", merged_comps_bf$FP),
TN =sprintf("%.2f", merged_comps_bf$TN), 
FN =sprintf("%.2f", merged_comps_bf$FN))

openxlsx::write.xlsx(table_df,file="~/Results_table.xlsx", rowNames =T)


```

### Metric figures CL24 (BFMC)

```{r metric fig CL BFMC}

###1 Cutoff
merged_comps_bf <- read_xlsx("~/Results.xlsx")
merged_comps_bf <- merged_comps_bf[,2:24]

###Assemble plot data in way required for plots
plot_acc <- cbind(merged_comps_bf[0:2, 1], merged_comps_bf[0:2,2:4])
colnames(plot_acc) <- c("Method", "Measure1", "ci_low", "ci_high")
plot_acc$Measure <- c("Accuracy", "Accuracy")

plot_ppv <- cbind(merged_comps_bf[0:2, 1], merged_comps_bf[0:2,5:7])
colnames(plot_ppv) <- c("Method", "Measure1", "ci_low", "ci_high")
plot_ppv$Measure <- c("PPV", "PPV")

plot_npv <- cbind(merged_comps_bf[0:2, 1], merged_comps_bf[0:2,8:10])
colnames(plot_npv) <- c("Method", "Measure1", "ci_low", "ci_high")
plot_npv$Measure <- c("NPV", "NPV")

plotdata <- rbind(plot_acc, plot_ppv, plot_npv)
plotdata1 <- plotdata
plotdata1$Method2 <- as.factor(c("2", "1"))

group_order <- c("NPV", "PPV", "Accuracy")
tick_positions <- seq(70, 100, by = 10)

###Forest plot Acc, PPV, NPV
ggplot(data=plotdata1, aes(y = factor(Measure, levels=group_order), x = Measure1 * 100, color=Method2, fill=Method2))+
  geom_vline(xintercept = tick_positions, color = "grey80", linewidth = 0.5, alpha=0.4) +
  geom_errorbar(aes(xmin = ci_low * 100, xmax = ci_high * 100),
                width = 0, linewidth = 0.75, position = position_dodge(width = 0.6)) +
  geom_point(position = position_dodge(width = 0.6), size = 1.75, stroke = 0.7)+
  scale_x_continuous(limits=c(70,110),breaks = seq(70,110, by=10),expand =c(0,0))+
  labs(x = "Percentage", y = "") +
  geom_text(aes(label = sprintf("%.f (%.f-%.f)", Measure1 * 100, ci_low * 100, ci_high * 100), group=Method2, x=106),
            position = position_dodge(width = 0.6), size = 2) +
  scale_color_manual(values=c("#295dbf", "#c52851"), guide="none")+
  scale_fill_manual(values=c("#295dbf", "#c52851"), guide="none")+
  theme_classic()+ 
  theme(axis.text.x = element_text(size = 7,color="grey30"),
        axis.text.y = element_text(size = 7, color="black"),
        axis.title.x = element_text(size = 7,color="black"),
        axis.ticks.y = element_blank(),
        legend.text = element_text(size = 6,color="black"),  
        legend.title = element_blank(), 
        legend.position = "bottom")

###2 Cutoffs
merged_comps_bf <- read_xlsx("~/Results.xlsx")
merged_comps_bf <- merged_comps_bf[,2:24]

###Assemble plot data in way required for plots
plot_acc <- cbind(merged_comps_bf[3:4, 1], merged_comps_bf[3:4,2:4])
colnames(plot_acc) <- c("Method", "Measure1", "ci_low", "ci_high")
plot_acc$Measure <- c("Accuracy", "Accuracy")

plot_ppv <- cbind(merged_comps_bf[3:4, 1], merged_comps_bf[3:4,5:7])
colnames(plot_ppv) <- c("Method", "Measure1", "ci_low", "ci_high")
plot_ppv$Measure <- c("PPV", "PPV")

plot_npv <- cbind(merged_comps_bf[3:4, 1], merged_comps_bf[3:4,8:10])
colnames(plot_npv) <- c("Method", "Measure1", "ci_low", "ci_high")
plot_npv$Measure <- c("NPV", "NPV")

plotdata <- rbind(plot_acc, plot_ppv, plot_npv)
plotdata1 <- plotdata
plotdata1$Method2 <- as.factor(c("2", "1"))

group_order <- c("NPV", "PPV", "Accuracy")
tick_positions <- seq(70, 100, by = 10)

###Forest plot Acc, PPV, NPV
ggplot(data=plotdata1, aes(y = factor(Measure, levels=group_order), x = Measure1 * 100, color=Method2, fill=Method2))+
  geom_vline(xintercept = tick_positions, color = "grey80", linewidth = 0.5, alpha=0.4) +
  geom_errorbar(aes(xmin = ci_low * 100, xmax = ci_high * 100),
                width = 0, linewidth = 0.75, position = position_dodge(width = 0.6)) +
  geom_point(position = position_dodge(width = 0.6), size = 1.75, stroke = 0.7)+
  scale_x_continuous(limits=c(70,110),breaks = seq(70,110, by=10),expand =c(0,0))+
  labs(x = "Percentage", y = "") +
  geom_text(aes(label = sprintf("%.f (%.f-%.f)", Measure1 * 100, ci_low * 100, ci_high * 100), group=Method2, x=106),
            position = position_dodge(width = 0.6), size = 2) +
  scale_color_manual(values=c("#295dbf", "#c52851"), guide="none")+
  scale_fill_manual(values=c("#295dbf", "#c52851"), guide="none")+
  theme_classic()+ 
  theme(axis.text.x = element_text(size = 7,color="grey30"),
        axis.text.y = element_text(size = 7, color="black"),
        axis.title.x = element_text(size = 7,color="black"),
        axis.ticks.y = element_blank(),
        legend.text = element_text(size = 6,color="black"),  
        legend.title = element_blank(), 
        legend.position = "bottom")

###Intermediate plot
plot_grey <- cbind(merged_comps_bf[3:4, 1], merged_comps_bf[3:4, 21:23])
colnames(plot_grey) <- c("Method", "Measure1", "ci_low", "ci_high")
group_order <- c("Plasma p-tau217/AB42", "CSF AB42/40")

ggplot(data=plot_grey, aes(x=factor(Method,levels = c("Plasma p-tau217/AB42", "CSF AB42/40")),y=Measure1, fill=factor(Method, levels = c("Plasma p-tau217/AB42", "CSF AB42/40"))))+
  geom_bar(color="black",stat = "identity", alpha=0.8, width=0.6,  position = position_dodge(width = 0.1),)+
  geom_errorbar(aes(x=factor(Method,level = c("Plasma p-tau217/AB42", "CSF AB42/40")), ymax = ci_high, ymin = ci_low),width=0.2, size =0.5,position=position_dodge(0.1),  color="black")+
  scale_y_continuous(limits=c(0,40),breaks = seq(0,40, by=10),expand =c(0,0))+
  geom_text(aes(label = sprintf("%.1f", Measure1)), position = position_dodge(width=0.75), vjust=-3, size = 2) +
  scale_fill_manual(values = c("#c52851", "#295dbf"), guide="none") +
  labs(title = element_blank(),x = "",y = "Intermediate values (%)") +
  theme_classic()+
  theme(axis.text.y = element_text(size=6),
        axis.text.x = element_text(size=6),
        axis.title.x = element_text(size=6),
        axis.title.y= element_text(size=6),
        panel.border = element_rect(linewidth = 0.5, fill = NA, color=NA))  

```

# 2. BioFINDER-Primary care

------------------------------------------------------------------------

```{r set up data BFPC}
#| echo: false
df <- read_xlsx("~/d2.xlsx")

```

## 2A. VR outcome

### Boxplots VR (BFPC)

```{r boxplots VR BFPC}
df$petstat <- as.factor(df$VR_overall)

ggplot(df, aes(x = petstat, y = PL_217_42, fill=petstat)) +
  annotate("rect", xmin = -Inf, xmax = Inf, ymin = 0.0037, ymax = 0.0074,
           fill = "grey80", alpha = 0.4) +
  geom_violin(alpha=0.3) +
  geom_hline(yintercept=0.00738, linetype="dashed", color="grey20", alpha=.8, linewidth = .35) +
  geom_hline(yintercept=0.0037, linetype="dashed", color="grey20", alpha = .8, linewidth = .35) +
  geom_quasirandom(alpha = 0.75, size = 1,shape=21, color="black", stroke=0.25) +
  scale_y_continuous(breaks = round(seq(0, 0.1, by = 0.025), 3), limits = c(0, 0.085)) +
  scale_x_discrete(labels=c("0" ="VR-","1" ="VR+")) +
  labs(x = "AD status", y = "Plasma p-tau217/AB42") +
  scale_fill_manual(values = c("#afafaf", "#c52851"), guide = "none") +
  theme_classic() +
  theme(axis.title.x = element_blank(),
        axis.title.y = element_text(size=7),
        axis.text.x = element_text(size=6),
        axis.text.y = element_text(size=6))+
  stat_compare_means(method="t.test", label="p.signif", label.x = 1.5, label.y = 0.04)

##CSF
ggplot(df, aes(x = petstat, y = csf_4240, fill=petstat)) +
  annotate("rect", xmin = -Inf, xmax = Inf, ymin = 0.058, ymax = 0.072,
           fill = "grey80", alpha = 0.4) +
  geom_violin(alpha=0.3) +
  geom_hline(yintercept=0.058, linetype="dashed", color="grey20", alpha=.8, linewidth = .35) +
  geom_hline(yintercept=0.072, linetype="dashed", color="grey20", alpha = .8, linewidth = .35) +
  geom_quasirandom(alpha = 0.75, size = 1,shape=21, color="black", stroke=0.25) +
  scale_x_discrete(labels=c("0" ="VR-","1" ="VR+")) +
  labs(x = "AD status", y = "CSF AB42/40") +
  scale_fill_manual(values = c("#afafaf", "#295dbf"), guide = "none") +
  theme_classic() +
  theme(axis.title.x = element_blank(),
        axis.title.y = element_text(size=7),
        axis.text.x = element_text(size=6),
        axis.text.y = element_text(size=6))+
  stat_compare_means(method="t.test", label="p.signif", label.x = 1.5, label.y = 0.04)

```

### Analyses VR AUC (BFPC)

```{r BFPC,AB-PET VR outcome}
##AUC differences with DeLong
df$petstat <- as.factor(df$VR_overall)

#| echo: false
biomarkers <- c("PL_217_42", "ptau217", "csf_4240")
results_delong <- list()
index <- 1

library(pROC)

for (i in seq_along(biomarkers)){
  for (j in seq_along(biomarkers)){ 
    if (i < j) {
      predictor1 <- biomarkers[i]
      predictor2 <- biomarkers[j]
      
      formula1 <- as.formula(paste("petstat~",predictor1, collapse=""))
      formula2 <- as.formula(paste("petstat~",predictor2, collapse=""))
      
      roc_curve1 <- pROC::roc(formula1, data=df, quiet=T)
      roc_curve2 <- pROC::roc(formula2, data=df,quiet=T)
      
      res <- roc.test(roc_curve1, roc_curve2, method = "delong")
      
      long <- data.frame(
        comp = paste(predictor1, predictor2, sep=" vs. "),
        auc1a = round(roc_curve1$auc,3),
        auc2a = round(roc_curve2$auc,3),
        pval = round(res$p.value,3),
        auc1_ci_low = round(ci.auc(roc_curve1)[1],3),
        auc1_ci_high =round(ci.auc(roc_curve1)[3],3),
        auc2_ci_low =round(ci.auc(roc_curve2)[1],3),
        auc2_ci_high = round(ci.auc(roc_curve2)[3],3)
      )
      
      results_delong[[length(results_delong) + 1]] <- long
      index <- index + 1
    }
  }
}

results_delong <- do.call(rbind.data.frame, results_delong)
results_delong$padj <- round(p.adjust(results_delong$pval, method = "fdr"),3)
results_delong$auc_order <- c(results_delong$auc1a[1],results_delong$auc1a[3], results_delong$auc2a[3])
results_delong$auc_order_ci_low <- c(results_delong$auc1_ci_low[1],results_delong$auc1_ci_low[3], results_delong$auc2_ci_low[3])
results_delong$auc_order_ci_high <- c(results_delong$auc1_ci_high[1],results_delong$auc1_ci_high[3], results_delong$auc2_ci_high[3])
openxlsx::write.xlsx(results_delong,
                     file="~/DELONG_VR.xlsx")

##AUC plot
roc_curve2 <- pROC::roc(petstat ~ ptau217, data=df,quiet=T)
auc2 <- auc(roc_curve2)
roc_curve1 <- pROC::roc(petstat ~ PL_217_42, data=df,quiet=T)
auc1 <- auc(roc_curve1)
roc_curve3 <- pROC::roc(petstat ~ csf_4240, data=df,quiet=T)
auc3 <- auc(roc_curve3)

roc_list <- list(roc_curve1, roc_curve2, roc_curve3)

ggroc(roc_list) +
  scale_color_manual(values = c("#c52851", "#4ca481", "#295dbf"), 
                     labels = c("Plasma p-tau217/AB42", "Plasma p-tau217", "CSF AB42/40"), guide="none") +
  labs(title = element_blank(), x = "Specificity", y = "Sensitivity", color = "Assay") +
  scale_x_reverse()+
  scale_y_continuous()+
  geom_abline(slope = 1, intercept = 1, linetype = "dashed") +
  theme_classic()+
  theme(panel.border = element_blank(),
        axis.text.y = element_text(size = 5,color="grey30"),
        axis.text.x = element_text(size = 5,color="grey30"),
        axis.title.x = element_text(size=6,color="black"),
        axis.title.y = element_text(size=6),color="black")+
  annotate("text", x=0.3, y=0.25, 
           label = sprintf("%.2f (%.2f, %.2f)", auc(roc_curve1), ci.auc(roc_curve1)[1], ci.auc(roc_curve1)[3]),
           size = 2, color = "#c52851")+
  annotate("text", x=0.3, y=0.15, 
           label = sprintf("%.2f (%.2f, %.2f)", auc(roc_curve2), ci.auc(roc_curve2)[1], ci.auc(roc_curve2)[3]),
           size = 2, color = "#4ca481")+
  annotate("text", x=0.3, y=0.05, 
           label = sprintf("%.2f (%.2f, %.2f)", auc(roc_curve3), ci.auc(roc_curve3)[1], ci.auc(roc_curve3)[3]),
           size = 2, color = "#295dbf")

```

### Metrics VR (BFMC)

```{r metrics BFPC}
#| echo: false

df$petstat <- as.factor(df$VR_overall)

df$ptau217ab42_pos <- ifelse(df$PL_217_42 >= 0.00738, 1, 0) 
df$ptau217ab42_neg <- ifelse(df$PL_217_42 <= 0.00370, 0, 1)

df$ab4240_pos <- ifelse(df$csf_4240 <= 0.072, 1, 0)
df$ab4240_pos2 <- ifelse(df$csf_4240 <= 0.058, 1, 0)

##Calculate Accuracy, PPV, NPV and 95% CIs

f_comp_stats <- function(data, indices) {
  d <- as.data.frame(data[indices,])
  
  ##threshold calculation related to d, and then assign binary status based on that threshold
  compute_metrics <- function(true, pred) {
    
    ##threshold calculation and 
    
    v_tp <- sum(true == 1 & pred == 1)
    v_fp <- sum(true == 0 & pred == 1)
    v_tn <- sum(true == 0 & pred == 0)
    v_fn <- sum(true == 1 & pred == 0)
    
    sens <- v_tp / (v_tp + v_fn)
    spec <- v_tn / (v_tn + v_fp)
    acc <- (v_tp + v_tn) / (v_tp + v_tn + v_fn + v_fp)
    ppv <- cutpointr::ppv(tp = v_tp, fp = v_fp, tn = v_tn, fn = v_fn)
    npv <- cutpointr::npv(tp = v_tp, fp = v_fp, tn = v_tn, fn = v_fn)
    
    return(c(acc, ppv, npv, sens, spec, v_tp, v_fp, v_tn, v_fn))
  }
  
  test_columns <- c("ptau217ab42_pos", "ab4240_pos")
  results <- matrix(nrow = length(test_columns), ncol = 9)
  colnames(results) <- c("Accuracy", "PPV", "NPV", "Sensitivity", "Specificity", "TP", "FP", "TN", "FN")
  rownames(results) <- c("PL_217_42", "csf_4240")
  
  for (i in seq_along(test_columns)) {
    results[i, ] <- round(compute_metrics(d$petstat, d[[test_columns[i]]]),3)
  }
  
  #Assign p-tau217/AB42 metrics
  acc1 <- results[1,1]
  ppv1 <- results[1,2]
  npv1 <- results[1,3]
  sens1 <- results[1,4]
  spec1 <- results[1,5]
  tp1 <- results[1,6]
  fp1 <- results[1,7]
  tn1 <- results[1,8]
  fn1 <- results[1,9]
  
  #Assign CSF metrics
  acc2 <- results[2,1]
  ppv2 <- results[2,2]
  npv2 <- results[2,3]
  sens2 <- results[2,4]
  spec2 <- results[2,5]
  tp2 <- results[2,6]
  fp2 <- results[2,7]
  tn2 <- results[2,8]
  fn2 <- results[2,9]
  
  #p-tau217 vs. 217/ab42
  diff_acc <- acc1 - acc2
  diff_ppv <- ppv1 - ppv2
  diff_npv <- npv1 - npv2
  diff_sens <- sens1 - sens2

  
  return(c(acc1, acc2, ppv1, ppv2, npv1, npv2,#6
           diff_acc, diff_ppv, diff_npv, diff_sens,#10
           sens1, sens2, spec1, spec2, diff_sens, #15
           tp1, fp1, tn1, fn1, tp2, fp2, tn2, fn2)) #23
}   

set.seed(12345)
boot_results <- boot(data = df, statistic = f_comp_stats, R = 2000)

#Calculate pvalues 1 cutoff
stat_indices <- list(
  "Accuracy 217_AB42 vs. CSF" = 7,
  "PPV 217_AB42 vs. CSF" = 8,
  "NPV 217_AB42 vs. CSF" = 9)

pvals_1cp <- data.frame(
  Pval = numeric(length(stat_indices)),
  row.names = c("Accuracy 217_AB42 vs. CSF","PPV 217_AB42 vs. CSF","NPV 217_AB42 vs. CSF"))

bootstrap_replicates <- boot_results$t
for (stat_name in names(stat_indices)) {
  index <- stat_indices[[stat_name]]
  boot_diff <- boot_results$t0[index]
  results_underH0_diff <- bootstrap_replicates[, index] - mean(bootstrap_replicates[, index])
  p_value <- mean(abs(results_underH0_diff) >= abs(boot_diff))
  pvals_1cp[paste0(stat_name), "Pval"] <- round(p_value, 3)
}

##Add outcomes to dataframe (function to establish dataframe as desired)
create_df <- function(method_name, boot_acc_index, boot_ppv_index, boot_npv_index, boot_sen_index, boot_spec_index,boot_tp_index,boot_fp_index,boot_tn_index,boot_fn_index) {
  data.frame(
    method = method_name,
    accuracy = round(boot_results$t0[boot_acc_index], 3),
    acc_ci_lower = round(quantile(boot_results$t[, boot_acc_index], c(0.025, 0.975), na.rm=T)[1], 3),
    acc_ci_upper = round(quantile(boot_results$t[, boot_acc_index], c(0.025, 0.975), na.rm=T)[2], 3),
    PPV = round(boot_results$t0[boot_ppv_index], 3),
    ppv_ci_lower = round(quantile(boot_results$t[, boot_ppv_index], c(0.025, 0.975), na.rm=T)[1], 3),
    ppv_ci_upper = round(quantile(boot_results$t[, boot_ppv_index], c(0.025, 0.975), na.rm=T)[2], 3),
    NPV = round(boot_results$t0[boot_npv_index], 3),
    npv_ci_lower = round(quantile(boot_results$t[, boot_npv_index], c(0.025, 0.975), na.rm=T)[1], 3),
    npv_ci_upper = round(quantile(boot_results$t[, boot_npv_index], c(0.025, 0.975), na.rm=T)[2], 3),
    Sensitivity =round(boot_results$t0[boot_sen_index], 3),
    sen_ci_lower = round(quantile(boot_results$t[, boot_sen_index], c(0.025, 0.975), na.rm=T)[1], 3),
    sen_ci_upper = round(quantile(boot_results$t[, boot_sen_index], c(0.025, 0.975), na.rm=T)[2], 3),
    Specificity = round(boot_results$t0[boot_spec_index], 3),
    spec_ci_lower = round(quantile(boot_results$t[, boot_spec_index], c(0.025, 0.975), na.rm=T)[1], 3),
    spec_ci_upper = round(quantile(boot_results$t[, boot_spec_index], c(0.025, 0.975), na.rm=T)[2], 3),
    TP = round(boot_results$t0[boot_tp_index], 0),
    FP = round(boot_results$t0[boot_fp_index], 0),
    TN = round(boot_results$t0[boot_tn_index], 0),
    FN = round(boot_results$t0[boot_fn_index], 0),
    intermediate_n_percentage = NA,
    intermediate_n_percentage_low = NA,
    intermediate_n_percentage_high = NA,
    stringsAsFactors = FALSE,
    row.names = "1 Cutpoint"
  )
}

results_1cp_2 <- create_df(method_name = "Plasma p-tau217/AB42",boot_acc_index = 1,boot_ppv_index = 3,boot_npv_index = 5, boot_sen_index=11, boot_spec_index=13,boot_tp_index = 16, boot_fp_index=17, boot_tn_index=18, boot_fn_index=19)

results_1cp_3 <- create_df(method_name = "CSF AB42/40",boot_acc_index = 2,boot_ppv_index = 4,boot_npv_index = 6, boot_sen_index=12, boot_spec_index=14,boot_tp_index = 20, boot_fp_index=21, boot_tn_index=22, boot_fn_index=23)

merged_results_1cp <- rbind(results_1cp_2, results_1cp_3)

#Step 2: establish the intermediate zone

df <- df %>%
  mutate(greyzone_ptau217ab42 = case_when(
    ptau217ab42_neg == 0 ~ 1,  # sens95 equals 0
    ptau217ab42_pos == 1 ~ 3,  # spec95 equals 1
    TRUE ~ 2                     # Intermediate values
  ))

df <- df %>%
  mutate(greyzone_ab4240 = case_when(
    ab4240_pos == 0 ~ 1,  # sens95 equals 0 # so when they're negative 0.072
    ab4240_pos2 == 1 ~ 3,  # spec95 equals 1 #so when they're positive even 0.058
    TRUE ~ 2                     # Intermediate values
  ))

#table(df$greyzone_ab4240)

###Function to bootstrap %intermediate
f_greyzone <- function(data, indices){
  d <- data[indices, ]
  
  test_bio <- c("PL_217_42", "csf_ab4240")
  pred_pos <- c("ptau217ab42_pos", "ab4240_pos")
  pred_neg <- c("ptau217ab42_neg", "ab4240_pos2")
  
  for (i in seq_along(test_bio)) {
    greyzone_col <- paste0("greyzone_", test_bio[i])
    neg_col <- pred_neg[i]
    pos_col <- pred_pos[i]
    
    d <- d %>%
      mutate(!!greyzone_col := case_when(
        !!sym(neg_col) == 0 ~ 1,  # sens95 equals 0
        !!sym(pos_col) == 1 ~ 3,  # spec95 equals 1
        TRUE ~ 2
      ))  
  }
  
  int_n_ptau217ab42 <- length(which(d$greyzone_PL_217_42 ==2))
  int_perc_ptau217ab42 <- round((length(which(d$greyzone_PL_217_42 == 2)) / nrow(d)) * 100, 3)
  
  int_n_csf <- length(which(d$greyzone_ab4240 ==2))
  int_perc_csf <- round((length(which(d$greyzone_ab4240 == 2)) / nrow(d)) * 100, 3)
  
  #DIFFERENCES BETWEEN ASSAYS
  diff_perc_ptau217ab42_csf <- int_perc_ptau217ab42 - int_perc_csf
  
  return(c(int_perc_ptau217ab42,int_perc_csf, diff_perc_ptau217ab42_csf))
}

set.seed(12345)
boot_results_greyzone <- boot(data = df, statistic = f_greyzone, R = 2000)

##Calculate pvalue %intermediate differences
stat_indices <- list("Int% pval p-tau217/AB42 vs.CSF" = 3)

pvals_intermediate <- data.frame(
  Pval = numeric(length(stat_indices)),
  row.names = c("Int% pval p-tau217/AB42 vs.CSF"))

bootstrap_replicates_grey <- boot_results_greyzone$t

for (stat_name in names(stat_indices)) {
  index <- stat_indices[[stat_name]]
  boot_diff <- boot_results_greyzone$t0[index]
  results_underH0_diff <- bootstrap_replicates_grey[, index] - mean(bootstrap_replicates_grey[, index])
  p_value <- mean(abs(results_underH0_diff) >= abs(boot_diff))
  pvals_intermediate[paste0(stat_name), "Pval"] <- round(p_value, 3)
}

#Step 3: Two cutoff approach

f_comp_stats_2cp <- function(data, indices) {
  d <- as.data.frame(data[indices,])
  
  
  compute_metrics <- function(d,greyzone, true, pred) {
    
    dx <- d %>% filter(!!sym(greyzone) != 2)
    
    v_tp <- sum(dx[[true]] == 1 & dx[[pred]] == 1)
    v_fp <- sum(dx[[true]] == 0 & dx[[pred]] == 1)
    v_tn <- sum(dx[[true]] == 0 & dx[[pred]] == 0)
    v_fn <- sum(dx[[true]] == 1 & dx[[pred]] == 0)
    
    sens <- v_tp / (v_tp + v_fn)
    spec <- v_tn / (v_tn + v_fp)
    acc <- (v_tp + v_tn) / (v_tp + v_tn + v_fn + v_fp)
    ppv <- cutpointr::ppv(tp = v_tp, fp = v_fp, tn = v_tn, fn = v_fn)
    npv <- cutpointr::npv(tp = v_tp, fp = v_fp, tn = v_tn, fn = v_fn)
    
    return(c(acc, ppv, npv, sens, spec, v_tp, v_fp, v_tn, v_fn))
  }
  
  greyzones <- c("greyzone_ptau217ab42","greyzone_ab4240")
  test_columns <- c("ptau217ab42_pos", "ab4240_pos")
  true_label <- "petstat"
  
  results <- matrix(nrow = length(test_columns), ncol =9)
  colnames(results) <- c("Accuracy", "PPV", "NPV", "Sensitivity", "Specificity", "TP", "FP", "TN", "FN")
  rownames(results) <- c("PL_217_42", "csf_4240")
  
  for (i in seq_along(test_columns)) {
    results[i, ] <- round(compute_metrics(d, greyzone = greyzones[i], true = true_label, pred = test_columns[i]),3)
  }
  
  #P-tau217/AB42
  acc1 <- results[1,1]
  ppv1 <- results[1,2]
  npv1 <- results[1,3]
  sens1 <- results[1,4]
  spec1 <- results[1,5]
  tp1 <- results[1,6]
  fp1 <- results[1,7]
  tn1 <- results[1,8]
  fn1 <- results[1,9]
  
  #CSF
  acc2 <- results[2,1]
  ppv2 <- results[2,2]
  npv2 <- results[2,3]
  sens2 <- results[2,4]
  spec2 <- results[2,5]
  tp2 <- results[2,6]
  fp2 <- results[2,7]
  tn2 <- results[2,8]
  fn2 <- results[2,9]
  
  #p-tau217 vs. 217/ab42
  diff_acc <- acc1 - acc2
  diff_ppv <- ppv1 - ppv2
  diff_npv <- npv1 - npv2
  diff_sens <- sens1 - sens2
  
  
  return(c(acc1, acc2, ppv1, ppv2, npv1, npv2,#6
           diff_acc, diff_ppv, diff_npv, diff_sens,#10
           sens1, sens2, spec1, spec2, diff_sens, #15
           tp1, fp1, tn1, fn1, tp2, fp2, tn2, fn2)) #23
} 

set.seed(12345)
boot_results_2cp <- boot(data = df, statistic = f_comp_stats_2cp, R = 2000)

##Calculate pvalues two cutoffs
stat_indices <- list(
  "Accuracy 217_AB42 vs. CSF" = 7,
  "PPV 217_AB42 vs. CSF" = 8,
  "NPV 217_AB42 vs. CSF" = 9)

pvals_2cp <- data.frame(
  Pval = numeric(length(stat_indices)),
  row.names = c("Accuracy 217_AB42 vs. CSF","PPV 217_AB42 vs. CSF","NPV 217_AB42 vs. CSF"))

bootstrap_replicates_2 <- boot_results_2cp$t
for (stat_name in names(stat_indices)) {
  index <- stat_indices[[stat_name]]
  boot_diff <- boot_results_2cp$t0[index]
  results_underH0_diff <- bootstrap_replicates_2[, index] - mean(bootstrap_replicates_2[, index])
  p_value <- mean(abs(results_underH0_diff) >= abs(boot_diff))
  pvals_2cp[paste0(stat_name), "Pval"] <- round(p_value, 3)
}

##Add results to dataframe
create_df_2 <- function(method_name, boot_acc_index, boot_ppv_index, boot_npv_index,boot_grey_index,boot_sen_index, boot_spec_index,boot_tp_index,boot_fp_index,boot_tn_index,boot_fn_index) {
  data.frame(
    method = method_name,
    accuracy = round(boot_results_2cp$t0[boot_acc_index], 3),
    acc_ci_lower = round(quantile(boot_results_2cp$t[, boot_acc_index], c(0.025, 0.975), na.rm=T)[1], 3),
    acc_ci_upper = round(quantile(boot_results_2cp$t[, boot_acc_index], c(0.025, 0.975), na.rm=T)[2], 3),
    PPV = round(boot_results_2cp$t0[boot_ppv_index], 3),
    ppv_ci_lower = round(quantile(boot_results_2cp$t[, boot_ppv_index], c(0.025, 0.975), na.rm=T)[1], 3),
    ppv_ci_upper = round(quantile(boot_results_2cp$t[, boot_ppv_index], c(0.025, 0.975), na.rm=T)[2], 3),
    NPV = round(boot_results_2cp$t0[boot_npv_index], 3),
    npv_ci_lower = round(quantile(boot_results_2cp$t[, boot_npv_index], c(0.025, 0.975), na.rm=T)[1], 3),
    npv_ci_upper = round(quantile(boot_results_2cp$t[, boot_npv_index], c(0.025, 0.975), na.rm=T)[2], 3),
    Sensitivity =round(boot_results_2cp$t0[boot_sen_index], 3),
    sen_ci_lower = round(quantile(boot_results_2cp$t[, boot_sen_index], c(0.025, 0.975), na.rm=T)[1], 3),
    sen_ci_upper = round(quantile(boot_results_2cp$t[, boot_sen_index], c(0.025, 0.975), na.rm=T)[2], 3),
    Specificity = round(boot_results_2cp$t0[boot_spec_index], 3),
    spec_ci_lower = round(quantile(boot_results_2cp$t[, boot_spec_index], c(0.025, 0.975), na.rm=T)[1], 3),
    spec_ci_upper = round(quantile(boot_results_2cp$t[, boot_spec_index], c(0.025, 0.975), na.rm=T)[2], 3),
    TP = round(boot_results_2cp$t0[boot_tp_index], 0),
    FP = round(boot_results_2cp$t0[boot_fp_index], 0),
    TN = round(boot_results_2cp$t0[boot_tn_index], 0),
    FN = round(boot_results_2cp$t0[boot_fn_index], 0),
    intermediate_n_percentage = round(boot_results_greyzone$t0[boot_grey_index],3),
    intermediate_n_percentage_low = round(quantile(boot_results_greyzone$t[, boot_grey_index], c(0.025, 0.975), na.rm=T)[1], 3),
    intermediate_n_percentage_high = round(quantile(boot_results_greyzone$t[, boot_grey_index], c(0.025, 0.975), na.rm=T)[2], 3),
    stringsAsFactors = FALSE,
    row.names = "2 Cutpoints"
  )
}

results_2cp_2 <- create_df_2(method_name = "Plasma p-tau217/AB42",boot_acc_index = 1,boot_ppv_index = 3,boot_npv_index = 5, boot_grey_index = 1, boot_sen_index=11, boot_spec_index=13,boot_tp_index = 16, boot_fp_index=17, boot_tn_index=18, boot_fn_index=19)

results_2cp_3 <- create_df_2(method_name = "CSF AB42/40",boot_acc_index = 2,boot_ppv_index = 4,boot_npv_index = 6, boot_grey_index = 2, boot_sen_index=12, boot_spec_index=14,boot_tp_index = 20, boot_fp_index=21, boot_tn_index=22, boot_fn_index=23)

merged_results_2cp <- rbind(results_2cp_2, results_2cp_3)

#Step 4: Bind all datasets together
merged_comps_bf <- rbind(merged_results_1cp, merged_results_2cp)
merged_comps_bf$Cutpoints <- c("1 Cutpoint","1 Cutpoint","2 Cutpoints","2 Cutpoints")
openxlsx::write.xlsx(merged_comps_bf,file="~/Results.xlsx", rowNames =T)

pvalues_all <- rbind(
  pvals_1cp,
  pvals_intermediate,
  pvals_2cp
)
openxlsx::write.xlsx(pvalues_all,file="~/Results_pvals.xlsx", rowNames =T)


#Step 5: Create dataframe for manuscript tables
table_df <- data.frame(
Measure = merged_comps_bf$method,
Accuracy = sprintf("%.2f (%.2f-%.2f)", merged_comps_bf$accuracy, merged_comps_bf$acc_ci_lower, merged_comps_bf$acc_ci_upper),
PPV = sprintf("%.2f (%.2f-%.2f)", merged_comps_bf$PPV, merged_comps_bf$ppv_ci_lower, merged_comps_bf$ppv_ci_upper),
NPV = sprintf("%.2f (%.2f-%.2f)", merged_comps_bf$NPV, merged_comps_bf$npv_ci_lower, merged_comps_bf$npv_ci_upper),
Gre= sprintf("%.2f (%.2f-%.2f)", merged_comps_bf$intermediate_n_percentage, merged_comps_bf$intermediate_n_percentage_low, merged_comps_bf$intermediate_n_percentage_high),
Sensitivity = sprintf("%.2f (%.2f-%.2f)", merged_comps_bf$Sensitivity, merged_comps_bf$sen_ci_lower, merged_comps_bf$sen_ci_upper),
Specificity =sprintf("%.2f (%.2f-%.2f)", merged_comps_bf$Specificity, merged_comps_bf$spec_ci_lower, merged_comps_bf$spec_ci_upper), 
TP =sprintf("%.2f", merged_comps_bf$TP),
FP =sprintf("%.2f", merged_comps_bf$FP),
TN =sprintf("%.2f", merged_comps_bf$TN), 
FN =sprintf("%.2f", merged_comps_bf$FN))

openxlsx::write.xlsx(table_df,file="~/Results_table.xlsx", rowNames =T)

```

### Metric figures VR (BFPC)

```{r metric fig VR BFPC}

###1 Cutoff
merged_comps_bf <- read_xlsx("~/Results.xlsx")
merged_comps_bf <- merged_comps_bf[,2:24]

###Assemble plot data in way required for plots
plot_acc <- cbind(merged_comps_bf[0:2, 1], merged_comps_bf[0:2,2:4])
colnames(plot_acc) <- c("Method", "Measure1", "ci_low", "ci_high")
plot_acc$Measure <- c("Accuracy", "Accuracy")

plot_ppv <- cbind(merged_comps_bf[0:2, 1], merged_comps_bf[0:2,5:7])
colnames(plot_ppv) <- c("Method", "Measure1", "ci_low", "ci_high")
plot_ppv$Measure <- c("PPV", "PPV")

plot_npv <- cbind(merged_comps_bf[0:2, 1], merged_comps_bf[0:2,8:10])
colnames(plot_npv) <- c("Method", "Measure1", "ci_low", "ci_high")
plot_npv$Measure <- c("NPV", "NPV")

plotdata <- rbind(plot_acc, plot_ppv, plot_npv)
plotdata1 <- plotdata
plotdata1$Method2 <- as.factor(c("2", "1"))

group_order <- c("NPV", "PPV", "Accuracy")
tick_positions <- seq(70, 100, by = 10)

###Forest plot Acc, PPV, NPV
ggplot(data=plotdata1, aes(y = factor(Measure, levels=group_order), x = Measure1 * 100, color=Method2, fill=Method2))+
  geom_vline(xintercept = tick_positions, color = "grey80", linewidth = 0.5, alpha=0.4) +
  geom_errorbar(aes(xmin = ci_low * 100, xmax = ci_high * 100),
                width = 0, linewidth = 0.75, position = position_dodge(width = 0.6)) +
  geom_point(position = position_dodge(width = 0.6), size = 1.75, stroke = 0.7)+
  scale_x_continuous(limits=c(70,110),breaks = seq(70,110, by=10),expand =c(0,0))+
  labs(x = "Percentage", y = "") +
  geom_text(aes(label = sprintf("%.f (%.f-%.f)", Measure1 * 100, ci_low * 100, ci_high * 100), group=Method2, x=106),
            position = position_dodge(width = 0.6), size = 2) +
  scale_color_manual(values=c("#295dbf", "#c52851"), guide="none")+
  scale_fill_manual(values=c("#295dbf", "#c52851"), guide="none")+
  theme_classic()+ 
  theme(axis.text.x = element_text(size = 7,color="grey30"),
        axis.text.y = element_text(size = 7, color="black"),
        axis.title.x = element_text(size = 7,color="black"),
        axis.ticks.y = element_blank(),
        legend.text = element_text(size = 6,color="black"),  
        legend.title = element_blank(), 
        legend.position = "bottom")

###2 Cutoffs
merged_comps_bf <- read_xlsx("~/Results.xlsx")
merged_comps_bf <- merged_comps_bf[,2:24]

###Assemble plot data in way required for plots
plot_acc <- cbind(merged_comps_bf[3:4, 1], merged_comps_bf[3:4,2:4])
colnames(plot_acc) <- c("Method", "Measure1", "ci_low", "ci_high")
plot_acc$Measure <- c("Accuracy", "Accuracy")

plot_ppv <- cbind(merged_comps_bf[3:4, 1], merged_comps_bf[3:4,5:7])
colnames(plot_ppv) <- c("Method", "Measure1", "ci_low", "ci_high")
plot_ppv$Measure <- c("PPV", "PPV")

plot_npv <- cbind(merged_comps_bf[3:4, 1], merged_comps_bf[3:4,8:10])
colnames(plot_npv) <- c("Method", "Measure1", "ci_low", "ci_high")
plot_npv$Measure <- c("NPV", "NPV")

plotdata <- rbind(plot_acc, plot_ppv, plot_npv)
plotdata1 <- plotdata
plotdata1$Method2 <- as.factor(c("2", "1"))

group_order <- c("NPV", "PPV", "Accuracy")
tick_positions <- seq(70, 100, by = 10)

###Forest plot Acc, PPV, NPV
ggplot(data=plotdata1, aes(y = factor(Measure, levels=group_order), x = Measure1 * 100, color=Method2, fill=Method2))+
  geom_vline(xintercept = tick_positions, color = "grey80", linewidth = 0.5, alpha=0.4) +
  geom_errorbar(aes(xmin = ci_low * 100, xmax = ci_high * 100),
                width = 0, linewidth = 0.75, position = position_dodge(width = 0.6)) +
  geom_point(position = position_dodge(width = 0.6), size = 1.75, stroke = 0.7)+
  scale_x_continuous(limits=c(70,110),breaks = seq(70,110, by=10),expand =c(0,0))+
  labs(x = "Percentage", y = "") +
  geom_text(aes(label = sprintf("%.f (%.f-%.f)", Measure1 * 100, ci_low * 100, ci_high * 100), group=Method2, x=106),
            position = position_dodge(width = 0.6), size = 2) +
  scale_color_manual(values=c("#295dbf", "#c52851"), guide="none")+
  scale_fill_manual(values=c("#295dbf", "#c52851"), guide="none")+
  theme_classic()+ 
  theme(axis.text.x = element_text(size = 7,color="grey30"),
        axis.text.y = element_text(size = 7, color="black"),
        axis.title.x = element_text(size = 7,color="black"),
        axis.ticks.y = element_blank(),
        legend.text = element_text(size = 6,color="black"),  
        legend.title = element_blank(), 
        legend.position = "bottom")

###Intermediate plot
plot_grey <- cbind(merged_comps_bf[3:4, 1], merged_comps_bf[3:4, 21:23])
colnames(plot_grey) <- c("Method", "Measure1", "ci_low", "ci_high")
group_order <- c("Plasma p-tau217/AB42", "CSF AB42/40")

ggplot(data=plot_grey, aes(x=factor(Method,levels = c("Plasma p-tau217/AB42", "CSF AB42/40")),y=Measure1, fill=factor(Method, levels = c("Plasma p-tau217/AB42", "CSF AB42/40"))))+
  geom_bar(color="black",stat = "identity", alpha=0.8, width=0.6,  position = position_dodge(width = 0.1),)+
  geom_errorbar(aes(x=factor(Method,level = c("Plasma p-tau217/AB42", "CSF AB42/40")), ymax = ci_high, ymin = ci_low),width=0.2, size =0.5,position=position_dodge(0.1),  color="black")+
  scale_y_continuous(limits=c(0,40),breaks = seq(0,40, by=10),expand =c(0,0))+
  geom_text(aes(label = sprintf("%.1f", Measure1)), position = position_dodge(width=0.75), vjust=-3, size = 2) +
  scale_fill_manual(values = c("#c52851", "#295dbf"), guide="none") +
  labs(title = element_blank(),x = "",y = "Intermediate values (%)") +
  theme_classic()+
  theme(axis.text.y = element_text(size=6),
        axis.text.x = element_text(size=6),
        axis.title.x = element_text(size=6),
        axis.title.y= element_text(size=6),
        panel.border = element_rect(linewidth = 0.5, fill = NA, color=NA))  

```

## 2B. Centiloids 24 outcome

------------------------------------------------------------------------

### Boxplots CL (BFPC)

```{r boxplots CL BFPC}
df$petstat <- as.factor(ifelse(df$CL_fnc_ber_com_composite >= 24, 1, 0)) 
df <- df %>% drop_na(petstat)


ggplot(df, aes(x = petstat, y = PL_217_42, fill=petstat)) +
  annotate("rect", xmin = -Inf, xmax = Inf, ymin = 0.0037, ymax = 0.0074,
           fill = "grey80", alpha = 0.4) +
  geom_violin(alpha=0.3) +
  geom_hline(yintercept=0.00738, linetype="dashed", color="grey20", alpha=.8, linewidth = .35) +
  geom_hline(yintercept=0.0037, linetype="dashed", color="grey20", alpha = .8, linewidth = .35) +
  geom_quasirandom(alpha = 0.75, size = 1,shape=21, color="black", stroke=0.25) +
  scale_y_continuous(breaks = round(seq(0, 0.1, by = 0.025), 3), limits = c(0, 0.085)) +
  scale_x_discrete(labels=c("0" ="VR-","1" ="VR+")) +
  labs(x = "AD status", y = "Plasma p-tau217/AB42") +
  scale_fill_manual(values = c("#afafaf", "#c52851"), guide = "none") +
  theme_classic() +
  theme(axis.title.x = element_blank(),
        axis.title.y = element_text(size=7),
        axis.text.x = element_text(size=6),
        axis.text.y = element_text(size=6))+
  stat_compare_means(method="t.test", label="p.signif", label.x = 1.5, label.y = 0.04)

##CSF
ggplot(df, aes(x = petstat, y = csf_4240, fill=petstat)) +
  annotate("rect", xmin = -Inf, xmax = Inf, ymin = 0.058, ymax = 0.072,
           fill = "grey80", alpha = 0.4) +
  geom_violin(alpha=0.3) +
  geom_hline(yintercept=0.058, linetype="dashed", color="grey20", alpha=.8, linewidth = .35) +
  geom_hline(yintercept=0.072, linetype="dashed", color="grey20", alpha = .8, linewidth = .35) +
  geom_quasirandom(alpha = 0.75, size = 1,shape=21, color="black", stroke=0.25) +
  scale_x_discrete(labels=c("0" ="VR-","1" ="VR+")) +
  labs(x = "AD status", y = "CSF AB42/40") +
  scale_fill_manual(values = c("#afafaf", "#295dbf"), guide = "none") +
  theme_classic() +
  theme(axis.title.x = element_blank(),
        axis.title.y = element_text(size=7),
        axis.text.x = element_text(size=6),
        axis.text.y = element_text(size=6))+
  stat_compare_means(method="t.test", label="p.signif", label.x = 1.5, label.y = 0.04)

```

### Analyses CL24 AUC (BFPC)

```{r BFPC,AB-PET CL24 outcome}
##AUC differences with DeLong
df$petstat <- as.factor(ifelse(df$CL_fnc_ber_com_composite >= 24, 1, 0)) 

#| echo: false
biomarkers <- c("PL_217_42", "ptau217","csf_4240")
results_delong <- list()
index <- 1

library(pROC)

for (i in seq_along(biomarkers)){
  for (j in seq_along(biomarkers)){ 
    if (i < j) {
      predictor1 <- biomarkers[i]
      predictor2 <- biomarkers[j]
      
      formula1 <- as.formula(paste("petstat~",predictor1, collapse=""))
      formula2 <- as.formula(paste("petstat~",predictor2, collapse=""))
      
      roc_curve1 <- pROC::roc(formula1, data=df, quiet=T)
      roc_curve2 <- pROC::roc(formula2, data=df,quiet=T)
      
      res <- roc.test(roc_curve1, roc_curve2, method = "delong")
      
      long <- data.frame(
        comp = paste(predictor1, predictor2, sep=" vs. "),
        auc1a = round(roc_curve1$auc,3),
        auc2a = round(roc_curve2$auc,3),
        pval = round(res$p.value,3),
        auc1_ci_low = round(ci.auc(roc_curve1)[1],3),
        auc1_ci_high =round(ci.auc(roc_curve1)[3],3),
        auc2_ci_low =round(ci.auc(roc_curve2)[1],3),
        auc2_ci_high = round(ci.auc(roc_curve2)[3],3)
      )
      
      results_delong[[length(results_delong) + 1]] <- long
      index <- index + 1
    }
  }
}

results_delong <- do.call(rbind.data.frame, results_delong)
results_delong$padj <- round(p.adjust(results_delong$pval, method = "fdr"),3)
results_delong$auc_order <- c(results_delong$auc1a[1],results_delong$auc1a[3], results_delong$auc2a[3])
results_delong$auc_order_ci_low <- c(results_delong$auc1_ci_low[1],results_delong$auc1_ci_low[3], results_delong$auc2_ci_low[3])
results_delong$auc_order_ci_high <- c(results_delong$auc1_ci_high[1],results_delong$auc1_ci_high[3], results_delong$auc2_ci_high[3])
openxlsx::write.xlsx(results_delong,
                     file="~/DELONG_VR.xlsx")

##AUC plot
roc_curve2 <- pROC::roc(petstat ~ ptau217, data=df,quiet=T)
auc2 <- auc(roc_curve2)
roc_curve1 <- pROC::roc(petstat ~ PL_217_42, data=df,quiet=T)
auc1 <- auc(roc_curve1)
roc_curve3 <- pROC::roc(petstat ~ csf_4240, data=df,quiet=T)
auc3 <- auc(roc_curve3)

roc_list <- list(roc_curve1, roc_curve2, roc_curve3)

ggroc(roc_list) +
  scale_color_manual(values = c("#c52851", "#4ca481", "#295dbf"), 
                     labels = c("Plasma p-tau217/AB42", "Plasma p-tau217", "CSF AB42/40"), guide="none") +
  labs(title = element_blank(), x = "Specificity", y = "Sensitivity", color = "Assay") +
  scale_x_reverse()+
  scale_y_continuous()+
  geom_abline(slope = 1, intercept = 1, linetype = "dashed") +
  theme_classic()+
  theme(panel.border = element_blank(),
        axis.text.y = element_text(size = 5,color="grey30"),
        axis.text.x = element_text(size = 5,color="grey30"),
        axis.title.x = element_text(size=6,color="black"),
        axis.title.y = element_text(size=6),color="black")+
  annotate("text", x=0.3, y=0.25, 
           label = sprintf("%.2f (%.2f, %.2f)", auc(roc_curve1), ci.auc(roc_curve1)[1], ci.auc(roc_curve1)[3]),
           size = 2, color = "#c52851")+
  annotate("text", x=0.3, y=0.15, 
           label = sprintf("%.2f (%.2f, %.2f)", auc(roc_curve2), ci.auc(roc_curve2)[1], ci.auc(roc_curve2)[3]),
           size = 2, color = "#4ca481")+
  annotate("text", x=0.3, y=0.05, 
           label = sprintf("%.2f (%.2f, %.2f)", auc(roc_curve3), ci.auc(roc_curve3)[1], ci.auc(roc_curve3)[3]),
           size = 2, color = "#295dbf")
```

### Metrics CL24 (BFPC)

```{r metrics CL24 BFPC}
df$petstat <- as.factor(ifelse(df$CL_fnc_ber_com_composite >= 24, 1, 0)) 

df$ptau217ab42_pos <- ifelse(df$PL_217_42 >= 0.00738, 1, 0) 
df$ptau217ab42_neg <- ifelse(df$PL_217_42 <= 0.00370, 0, 1)

df$ab4240_pos <- ifelse(df$csf_4240 <= 0.072, 1, 0)
df$ab4240_pos2 <- ifelse(df$csf_4240 <= 0.058, 1, 0)

##Calculate Accuracy, PPV, NPV and 95% CIs

f_comp_stats <- function(data, indices) {
  d <- as.data.frame(data[indices,])
  
  ##threshold calculation related to d, and then assign binary status based on that threshold
  compute_metrics <- function(true, pred) {
    
    ##threshold calculation and 
    
    v_tp <- sum(true == 1 & pred == 1)
    v_fp <- sum(true == 0 & pred == 1)
    v_tn <- sum(true == 0 & pred == 0)
    v_fn <- sum(true == 1 & pred == 0)
    
    sens <- v_tp / (v_tp + v_fn)
    spec <- v_tn / (v_tn + v_fp)
    acc <- (v_tp + v_tn) / (v_tp + v_tn + v_fn + v_fp)
    ppv <- cutpointr::ppv(tp = v_tp, fp = v_fp, tn = v_tn, fn = v_fn)
    npv <- cutpointr::npv(tp = v_tp, fp = v_fp, tn = v_tn, fn = v_fn)
    
    return(c(acc, ppv, npv, sens, spec, v_tp, v_fp, v_tn, v_fn))#sens#spec
  }
  
  test_columns <- c("ptau217ab42_pos", "ab4240_pos")
  results <- matrix(nrow = length(test_columns), ncol = 9)
  colnames(results) <- c("Accuracy", "PPV", "NPV", "Sensitivity", "Specificity", "TP", "FP", "TN", "FN")
  rownames(results) <- c("PL_217_42", "csf_4240")
  
  for (i in seq_along(test_columns)) {
    results[i, ] <- round(compute_metrics(d$petstat, d[[test_columns[i]]]),3)
  }
  
  #Assign p-tau217/AB42 metrics
  acc1 <- results[1,1]
  ppv1 <- results[1,2]
  npv1 <- results[1,3]
  sens1 <- results[1,4]
  spec1 <- results[1,5]
  tp1 <- results[1,6]
  fp1 <- results[1,7]
  tn1 <- results[1,8]
  fn1 <- results[1,9]
  
  #Assign CSF metrics
  acc2 <- results[2,1]
  ppv2 <- results[2,2]
  npv2 <- results[2,3]
  sens2 <- results[2,4]
  spec2 <- results[2,5]
  tp2 <- results[2,6]
  fp2 <- results[2,7]
  tn2 <- results[2,8]
  fn2 <- results[2,9]
  
  #p-tau217 vs. 217/ab42
  diff_acc <- acc1 - acc2
  diff_ppv <- ppv1 - ppv2
  diff_npv <- npv1 - npv2
  diff_sens <- sens1 - sens2
  
  
  return(c(acc1, acc2, ppv1, ppv2, npv1, npv2,#6
           diff_acc, diff_ppv, diff_npv, diff_sens,#10
           sens1, sens2, spec1, spec2, diff_sens, #15
           tp1, fp1, tn1, fn1, tp2, fp2, tn2, fn2)) #23
}   

set.seed(12345)
boot_results <- boot(data = df, statistic = f_comp_stats, R = 2000)

#Calculate pvalues 1 cutoff
stat_indices <- list(
  "Accuracy 217_AB42 vs. CSF" = 7,
  "PPV 217_AB42 vs. CSF" = 8,
  "NPV 217_AB42 vs. CSF" = 9)

pvals_1cp <- data.frame(
  Pval = numeric(length(stat_indices)),
  row.names = c("Accuracy 217_AB42 vs. CSF","PPV 217_AB42 vs. CSF","NPV 217_AB42 vs. CSF"))

bootstrap_replicates <- boot_results$t
for (stat_name in names(stat_indices)) {
  index <- stat_indices[[stat_name]]
  boot_diff <- boot_results$t0[index]
  results_underH0_diff <- bootstrap_replicates[, index] - mean(bootstrap_replicates[, index])
  p_value <- mean(abs(results_underH0_diff) >= abs(boot_diff))
  pvals_1cp[paste0(stat_name), "Pval"] <- round(p_value, 3)
}

##Add outcomes to dataframe (function to establish dataframe as desired)
create_df <- function(method_name, boot_acc_index, boot_ppv_index, boot_npv_index, boot_sen_index, boot_spec_index,boot_tp_index,boot_fp_index,boot_tn_index,boot_fn_index) {
  data.frame(
    method = method_name,
    accuracy = round(boot_results$t0[boot_acc_index], 3),
    acc_ci_lower = round(quantile(boot_results$t[, boot_acc_index], c(0.025, 0.975), na.rm=T)[1], 3),
    acc_ci_upper = round(quantile(boot_results$t[, boot_acc_index], c(0.025, 0.975), na.rm=T)[2], 3),
    PPV = round(boot_results$t0[boot_ppv_index], 3),
    ppv_ci_lower = round(quantile(boot_results$t[, boot_ppv_index], c(0.025, 0.975), na.rm=T)[1], 3),
    ppv_ci_upper = round(quantile(boot_results$t[, boot_ppv_index], c(0.025, 0.975), na.rm=T)[2], 3),
    NPV = round(boot_results$t0[boot_npv_index], 3),
    npv_ci_lower = round(quantile(boot_results$t[, boot_npv_index], c(0.025, 0.975), na.rm=T)[1], 3),
    npv_ci_upper = round(quantile(boot_results$t[, boot_npv_index], c(0.025, 0.975), na.rm=T)[2], 3),
    Sensitivity =round(boot_results$t0[boot_sen_index], 3),
    sen_ci_lower = round(quantile(boot_results$t[, boot_sen_index], c(0.025, 0.975), na.rm=T)[1], 3),
    sen_ci_upper = round(quantile(boot_results$t[, boot_sen_index], c(0.025, 0.975), na.rm=T)[2], 3),
    Specificity = round(boot_results$t0[boot_spec_index], 3),
    spec_ci_lower = round(quantile(boot_results$t[, boot_spec_index], c(0.025, 0.975), na.rm=T)[1], 3),
    spec_ci_upper = round(quantile(boot_results$t[, boot_spec_index], c(0.025, 0.975), na.rm=T)[2], 3),
    TP = round(boot_results$t0[boot_tp_index], 0),
    FP = round(boot_results$t0[boot_fp_index], 0),
    TN = round(boot_results$t0[boot_tn_index], 0),
    FN = round(boot_results$t0[boot_fn_index], 0),
    intermediate_n_percentage = NA,
    intermediate_n_percentage_low = NA,
    intermediate_n_percentage_high = NA,
    stringsAsFactors = FALSE,
    row.names = "1 Cutpoint"
  )
}

results_1cp_2 <- create_df(method_name = "Plasma p-tau217/AB42",boot_acc_index = 1,boot_ppv_index = 3,boot_npv_index = 5, boot_sen_index=11, boot_spec_index=13,boot_tp_index = 16, boot_fp_index=17, boot_tn_index=18, boot_fn_index=19)

results_1cp_3 <- create_df(method_name = "CSF AB42/40",boot_acc_index = 2,boot_ppv_index = 4,boot_npv_index = 6, boot_sen_index=12, boot_spec_index=14,boot_tp_index = 20, boot_fp_index=21, boot_tn_index=22, boot_fn_index=23)

merged_results_1cp <- rbind(results_1cp_2, results_1cp_3)

#Step 2: establish the intermediate zone

df <- df %>%
  mutate(greyzone_ptau217ab42 = case_when(
    ptau217ab42_neg == 0 ~ 1,  # sens95 equals 0
    ptau217ab42_pos == 1 ~ 3,  # spec95 equals 1
    TRUE ~ 2                     # Intermediate values
  ))

df <- df %>%
  mutate(greyzone_ab4240 = case_when(
    ab4240_pos == 0 ~ 1,  # sens95 equals 0 # so when they're negative 0.072
    ab4240_pos2 == 1 ~ 3,  # spec95 equals 1 #so when they're positive even 0.058
    TRUE ~ 2                     # Intermediate values
  ))

table(df$greyzone_ab4240)

###Function to bootstrap %intermediate
f_greyzone <- function(data, indices){
  d <- data[indices, ]
  
  test_bio <- c("PL_217_42", "csf_ab4240")
  pred_pos <- c("ptau217ab42_pos", "ab4240_pos")
  pred_neg <- c("ptau217ab42_neg", "ab4240_pos2")
  
  for (i in seq_along(test_bio)) {
    greyzone_col <- paste0("greyzone_", test_bio[i])
    neg_col <- pred_neg[i]
    pos_col <- pred_pos[i]
    
    d <- d %>%
      mutate(!!greyzone_col := case_when(
        !!sym(neg_col) == 0 ~ 1,  # sens95 equals 0
        !!sym(pos_col) == 1 ~ 3,  # spec95 equals 1
        TRUE ~ 2
      ))  
  }
  
  int_n_ptau217ab42 <- length(which(d$greyzone_PL_217_42 ==2))
  int_perc_ptau217ab42 <- round((length(which(d$greyzone_PL_217_42 == 2)) / nrow(d)) * 100, 3)
  
  int_n_csf <- length(which(d$greyzone_ab4240 ==2))
  int_perc_csf <- round((length(which(d$greyzone_ab4240 == 2)) / nrow(d)) * 100, 3)
  
  #DIFFERENCES BETWEEN ASSAYS
  diff_perc_ptau217ab42_csf <- int_perc_ptau217ab42 - int_perc_csf
  
  return(c(int_perc_ptau217ab42,int_perc_csf, diff_perc_ptau217ab42_csf))
}

set.seed(12345)
boot_results_greyzone <- boot(data = df, statistic = f_greyzone, R = 2000)

##Calculate pvalue %intermediate differences
stat_indices <- list("Int% pval p-tau217/AB42 vs.CSF" = 3)

pvals_intermediate <- data.frame(
  Pval = numeric(length(stat_indices)),
  row.names = c("Int% pval p-tau217/AB42 vs.CSF"))

bootstrap_replicates_grey <- boot_results_greyzone$t

for (stat_name in names(stat_indices)) {
  index <- stat_indices[[stat_name]]
  boot_diff <- boot_results_greyzone$t0[index]
  results_underH0_diff <- bootstrap_replicates_grey[, index] - mean(bootstrap_replicates_grey[, index])
  p_value <- mean(abs(results_underH0_diff) >= abs(boot_diff))
  pvals_intermediate[paste0(stat_name), "Pval"] <- round(p_value, 3)
}

#Step 3: Two cutoff approach

f_comp_stats_2cp <- function(data, indices) {
  d <- as.data.frame(data[indices,])
  
  
  compute_metrics <- function(d,greyzone, true, pred) {
    
    dx <- d %>% filter(!!sym(greyzone) != 2)
    
    v_tp <- sum(dx[[true]] == 1 & dx[[pred]] == 1)
    v_fp <- sum(dx[[true]] == 0 & dx[[pred]] == 1)
    v_tn <- sum(dx[[true]] == 0 & dx[[pred]] == 0)
    v_fn <- sum(dx[[true]] == 1 & dx[[pred]] == 0)
    
    sens <- v_tp / (v_tp + v_fn)
    spec <- v_tn / (v_tn + v_fp)
    acc <- (v_tp + v_tn) / (v_tp + v_tn + v_fn + v_fp)
    ppv <- cutpointr::ppv(tp = v_tp, fp = v_fp, tn = v_tn, fn = v_fn)
    npv <- cutpointr::npv(tp = v_tp, fp = v_fp, tn = v_tn, fn = v_fn)
    
    return(c(acc, ppv, npv, sens, spec, v_tp, v_fp, v_tn, v_fn))#sens#spec
  }
  
  greyzones <- c("greyzone_ptau217ab42","greyzone_ab4240")
  test_columns <- c("ptau217ab42_pos", "ab4240_pos")
  true_label <- "petstat"
  
  results <- matrix(nrow = length(test_columns), ncol =9)
  colnames(results) <- c("Accuracy", "PPV", "NPV", "Sensitivity", "Specificity", "TP", "FP", "TN", "FN")
  rownames(results) <- c("PL_217_42", "csf_4240")
  
  for (i in seq_along(test_columns)) {
    results[i, ] <- round(compute_metrics(d, greyzone = greyzones[i], true = true_label, pred = test_columns[i]),3)
  }
  
  #P-tau217/AB42
  acc1 <- results[1,1]
  ppv1 <- results[1,2]
  npv1 <- results[1,3]
  sens1 <- results[1,4]
  spec1 <- results[1,5]
  tp1 <- results[1,6]
  fp1 <- results[1,7]
  tn1 <- results[1,8]
  fn1 <- results[1,9]
  
  #CSF
  acc2 <- results[2,1]
  ppv2 <- results[2,2]
  npv2 <- results[2,3]
  sens2 <- results[2,4]
  spec2 <- results[2,5]
  tp2 <- results[2,6]
  fp2 <- results[2,7]
  tn2 <- results[2,8]
  fn2 <- results[2,9]
  
  #p-tau217 vs. 217/ab42
  diff_acc <- acc1 - acc2
  diff_ppv <- ppv1 - ppv2
  diff_npv <- npv1 - npv2
  diff_sens <- sens1 - sens2
  
  
  return(c(acc1, acc2, ppv1, ppv2, npv1, npv2,#6
           diff_acc, diff_ppv, diff_npv, diff_sens,#10
           sens1, sens2, spec1, spec2, diff_sens, #15
           tp1, fp1, tn1, fn1, tp2, fp2, tn2, fn2)) #23
} 

set.seed(12345)
boot_results_2cp <- boot(data = df, statistic = f_comp_stats_2cp, R = 2000)

##Calculate pvalues two cutoffs
stat_indices <- list(
  "Accuracy 217_AB42 vs. CSF" = 7,
  "PPV 217_AB42 vs. CSF" = 8,
  "NPV 217_AB42 vs. CSF" = 9)

pvals_2cp <- data.frame(
  Pval = numeric(length(stat_indices)),
  row.names = c("Accuracy 217_AB42 vs. CSF","PPV 217_AB42 vs. CSF","NPV 217_AB42 vs. CSF"))

bootstrap_replicates_2 <- boot_results_2cp$t
for (stat_name in names(stat_indices)) {
  index <- stat_indices[[stat_name]]
  boot_diff <- boot_results_2cp$t0[index]
  results_underH0_diff <- bootstrap_replicates_2[, index] - mean(bootstrap_replicates_2[, index])
  p_value <- mean(abs(results_underH0_diff) >= abs(boot_diff))
  pvals_2cp[paste0(stat_name), "Pval"] <- round(p_value, 3)
}

##Add results to dataframe
create_df_2 <- function(method_name, boot_acc_index, boot_ppv_index, boot_npv_index,boot_grey_index,boot_sen_index, boot_spec_index,boot_tp_index,boot_fp_index,boot_tn_index,boot_fn_index) {
  data.frame(
    method = method_name,
    accuracy = round(boot_results_2cp$t0[boot_acc_index], 3),
    acc_ci_lower = round(quantile(boot_results_2cp$t[, boot_acc_index], c(0.025, 0.975), na.rm=T)[1], 3),
    acc_ci_upper = round(quantile(boot_results_2cp$t[, boot_acc_index], c(0.025, 0.975), na.rm=T)[2], 3),
    PPV = round(boot_results_2cp$t0[boot_ppv_index], 3),
    ppv_ci_lower = round(quantile(boot_results_2cp$t[, boot_ppv_index], c(0.025, 0.975), na.rm=T)[1], 3),
    ppv_ci_upper = round(quantile(boot_results_2cp$t[, boot_ppv_index], c(0.025, 0.975), na.rm=T)[2], 3),
    NPV = round(boot_results_2cp$t0[boot_npv_index], 3),
    npv_ci_lower = round(quantile(boot_results_2cp$t[, boot_npv_index], c(0.025, 0.975), na.rm=T)[1], 3),
    npv_ci_upper = round(quantile(boot_results_2cp$t[, boot_npv_index], c(0.025, 0.975), na.rm=T)[2], 3),
    Sensitivity =round(boot_results_2cp$t0[boot_sen_index], 3),
    sen_ci_lower = round(quantile(boot_results_2cp$t[, boot_sen_index], c(0.025, 0.975), na.rm=T)[1], 3),
    sen_ci_upper = round(quantile(boot_results_2cp$t[, boot_sen_index], c(0.025, 0.975), na.rm=T)[2], 3),
    Specificity = round(boot_results_2cp$t0[boot_spec_index], 3),
    spec_ci_lower = round(quantile(boot_results_2cp$t[, boot_spec_index], c(0.025, 0.975), na.rm=T)[1], 3),
    spec_ci_upper = round(quantile(boot_results_2cp$t[, boot_spec_index], c(0.025, 0.975), na.rm=T)[2], 3),
    TP = round(boot_results_2cp$t0[boot_tp_index], 0),
    FP = round(boot_results_2cp$t0[boot_fp_index], 0),
    TN = round(boot_results_2cp$t0[boot_tn_index], 0),
    FN = round(boot_results_2cp$t0[boot_fn_index], 0),
    intermediate_n_percentage = round(boot_results_greyzone$t0[boot_grey_index],3),
    intermediate_n_percentage_low = round(quantile(boot_results_greyzone$t[, boot_grey_index], c(0.025, 0.975), na.rm=T)[1], 3),
    intermediate_n_percentage_high = round(quantile(boot_results_greyzone$t[, boot_grey_index], c(0.025, 0.975), na.rm=T)[2], 3),
    stringsAsFactors = FALSE,
    row.names = "2 Cutpoints"
  )
}

results_2cp_2 <- create_df_2(method_name = "Plasma p-tau217/AB42",boot_acc_index = 1,boot_ppv_index = 3,boot_npv_index = 5, boot_grey_index = 1, boot_sen_index=11, boot_spec_index=13,boot_tp_index = 16, boot_fp_index=17, boot_tn_index=18, boot_fn_index=19)

results_2cp_3 <- create_df_2(method_name = "CSF AB42/40",boot_acc_index = 2,boot_ppv_index = 4,boot_npv_index = 6, boot_grey_index = 2, boot_sen_index=12, boot_spec_index=14,boot_tp_index = 20, boot_fp_index=21, boot_tn_index=22, boot_fn_index=23)

merged_results_2cp <- rbind(results_2cp_2, results_2cp_3)

#Step 4: Bind all datasets together
merged_comps_bf <- rbind(merged_results_1cp, merged_results_2cp)
merged_comps_bf$Cutpoints <- c("1 Cutpoint","1 Cutpoint","2 Cutpoints","2 Cutpoints")
openxlsx::write.xlsx(merged_comps_bf,file="~/Results.xlsx", rowNames =T)

pvalues_all <- rbind(
  pvals_1cp,
  pvals_intermediate,
  pvals_2cp
)
openxlsx::write.xlsx(pvalues_all,file="~/Results_pvals.xlsx", rowNames =T)


#Step 5: Create dataframe for manuscript tables
table_df <- data.frame(
Measure = merged_comps_bf$method,
Accuracy = sprintf("%.2f (%.2f-%.2f)", merged_comps_bf$accuracy, merged_comps_bf$acc_ci_lower, merged_comps_bf$acc_ci_upper),
PPV = sprintf("%.2f (%.2f-%.2f)", merged_comps_bf$PPV, merged_comps_bf$ppv_ci_lower, merged_comps_bf$ppv_ci_upper),
NPV = sprintf("%.2f (%.2f-%.2f)", merged_comps_bf$NPV, merged_comps_bf$npv_ci_lower, merged_comps_bf$npv_ci_upper),
Gre= sprintf("%.2f (%.2f-%.2f)", merged_comps_bf$intermediate_n_percentage, merged_comps_bf$intermediate_n_percentage_low, merged_comps_bf$intermediate_n_percentage_high),
Sensitivity = sprintf("%.2f (%.2f-%.2f)", merged_comps_bf$Sensitivity, merged_comps_bf$sen_ci_lower, merged_comps_bf$sen_ci_upper),
Specificity =sprintf("%.2f (%.2f-%.2f)", merged_comps_bf$Specificity, merged_comps_bf$spec_ci_lower, merged_comps_bf$spec_ci_upper), 
TP =sprintf("%.2f", merged_comps_bf$TP),
FP =sprintf("%.2f", merged_comps_bf$FP),
TN =sprintf("%.2f", merged_comps_bf$TN), 
FN =sprintf("%.2f", merged_comps_bf$FN))

openxlsx::write.xlsx(table_df,file="~/Results_table.xlsx", rowNames =T)
```

### Metric figures CL (BFPC)

```{r metric fig CL BFPC}

###1 Cutoff
merged_comps_bf <- read_xlsx("~/Results.xlsx")
merged_comps_bf <- merged_comps_bf[,2:24]

###Assemble plot data in way required for plots
plot_acc <- cbind(merged_comps_bf[0:2, 1], merged_comps_bf[0:2,2:4])
colnames(plot_acc) <- c("Method", "Measure1", "ci_low", "ci_high")
plot_acc$Measure <- c("Accuracy", "Accuracy")

plot_ppv <- cbind(merged_comps_bf[0:2, 1], merged_comps_bf[0:2,5:7])
colnames(plot_ppv) <- c("Method", "Measure1", "ci_low", "ci_high")
plot_ppv$Measure <- c("PPV", "PPV")

plot_npv <- cbind(merged_comps_bf[0:2, 1], merged_comps_bf[0:2,8:10])
colnames(plot_npv) <- c("Method", "Measure1", "ci_low", "ci_high")
plot_npv$Measure <- c("NPV", "NPV")

plotdata <- rbind(plot_acc, plot_ppv, plot_npv)
plotdata1 <- plotdata
plotdata1$Method2 <- as.factor(c("2", "1"))

group_order <- c("NPV", "PPV", "Accuracy")
tick_positions <- seq(70, 100, by = 10)

###Forest plot Acc, PPV, NPV
ggplot(data=plotdata1, aes(y = factor(Measure, levels=group_order), x = Measure1 * 100, color=Method2, fill=Method2))+
  geom_vline(xintercept = tick_positions, color = "grey80", linewidth = 0.5, alpha=0.4) +
  geom_errorbar(aes(xmin = ci_low * 100, xmax = ci_high * 100),
                width = 0, linewidth = 0.75, position = position_dodge(width = 0.6)) +
  geom_point(position = position_dodge(width = 0.6), size = 1.75, stroke = 0.7)+
  scale_x_continuous(limits=c(70,110),breaks = seq(70,110, by=10),expand =c(0,0))+
  labs(x = "Percentage", y = "") +
  geom_text(aes(label = sprintf("%.f (%.f-%.f)", Measure1 * 100, ci_low * 100, ci_high * 100), group=Method2, x=106),
            position = position_dodge(width = 0.6), size = 2) +
  scale_color_manual(values=c("#295dbf", "#c52851"), guide="none")+
  scale_fill_manual(values=c("#295dbf", "#c52851"), guide="none")+
  theme_classic()+ 
  theme(axis.text.x = element_text(size = 7,color="grey30"),
        axis.text.y = element_text(size = 7, color="black"),
        axis.title.x = element_text(size = 7,color="black"),
        axis.ticks.y = element_blank(),
        legend.text = element_text(size = 6,color="black"),  
        legend.title = element_blank(), 
        legend.position = "bottom")

###2 Cutoffs
merged_comps_bf <- read_xlsx("~/Results.xlsx")
merged_comps_bf <- merged_comps_bf[,2:24]

###Assemble plot data in way required for plots
plot_acc <- cbind(merged_comps_bf[3:4, 1], merged_comps_bf[3:4,2:4])
colnames(plot_acc) <- c("Method", "Measure1", "ci_low", "ci_high")
plot_acc$Measure <- c("Accuracy", "Accuracy")

plot_ppv <- cbind(merged_comps_bf[3:4, 1], merged_comps_bf[3:4,5:7])
colnames(plot_ppv) <- c("Method", "Measure1", "ci_low", "ci_high")
plot_ppv$Measure <- c("PPV", "PPV")

plot_npv <- cbind(merged_comps_bf[3:4, 1], merged_comps_bf[3:4,8:10])
colnames(plot_npv) <- c("Method", "Measure1", "ci_low", "ci_high")
plot_npv$Measure <- c("NPV", "NPV")

plotdata <- rbind(plot_acc, plot_ppv, plot_npv)
plotdata1 <- plotdata
plotdata1$Method2 <- as.factor(c("2", "1"))

group_order <- c("NPV", "PPV", "Accuracy")
tick_positions <- seq(70, 100, by = 10)

###Forest plot Acc, PPV, NPV
ggplot(data=plotdata1, aes(y = factor(Measure, levels=group_order), x = Measure1 * 100, color=Method2, fill=Method2))+
  geom_vline(xintercept = tick_positions, color = "grey80", linewidth = 0.5, alpha=0.4) +
  geom_errorbar(aes(xmin = ci_low * 100, xmax = ci_high * 100),
                width = 0, linewidth = 0.75, position = position_dodge(width = 0.6)) +
  geom_point(position = position_dodge(width = 0.6), size = 1.75, stroke = 0.7)+
  scale_x_continuous(limits=c(70,110),breaks = seq(70,110, by=10),expand =c(0,0))+
  labs(x = "Percentage", y = "") +
  geom_text(aes(label = sprintf("%.f (%.f-%.f)", Measure1 * 100, ci_low * 100, ci_high * 100), group=Method2, x=106),
            position = position_dodge(width = 0.6), size = 2) +
  scale_color_manual(values=c("#295dbf", "#c52851"), guide="none")+
  scale_fill_manual(values=c("#295dbf", "#c52851"), guide="none")+
  theme_classic()+ 
  theme(axis.text.x = element_text(size = 7,color="grey30"),
        axis.text.y = element_text(size = 7, color="black"),
        axis.title.x = element_text(size = 7,color="black"),
        axis.ticks.y = element_blank(),
        legend.text = element_text(size = 6,color="black"),  
        legend.title = element_blank(), 
        legend.position = "bottom")

###Intermediate plot
plot_grey <- cbind(merged_comps_bf[3:4, 1], merged_comps_bf[3:4, 21:23])
colnames(plot_grey) <- c("Method", "Measure1", "ci_low", "ci_high")
group_order <- c("Plasma p-tau217/AB42", "CSF AB42/40")

ggplot(data=plot_grey, aes(x=factor(Method,levels = c("Plasma p-tau217/AB42", "CSF AB42/40")),y=Measure1, fill=factor(Method, levels = c("Plasma p-tau217/AB42", "CSF AB42/40"))))+
  geom_bar(color="black",stat = "identity", alpha=0.8, width=0.6,  position = position_dodge(width = 0.1),)+
  geom_errorbar(aes(x=factor(Method,level = c("Plasma p-tau217/AB42", "CSF AB42/40")), ymax = ci_high, ymin = ci_low),width=0.2, size =0.5,position=position_dodge(0.1),  color="black")+
  scale_y_continuous(limits=c(0,40),breaks = seq(0,40, by=10),expand =c(0,0))+
  geom_text(aes(label = sprintf("%.1f", Measure1)), position = position_dodge(width=0.75), vjust=-3, size = 2) +
  scale_fill_manual(values = c("#c52851", "#295dbf"), guide="none") +
  labs(title = element_blank(),x = "",y = "Intermediate values (%)") +
  theme_classic()+
  theme(axis.text.y = element_text(size=6),
        axis.text.x = element_text(size=6),
        axis.title.x = element_text(size=6),
        axis.title.y= element_text(size=6),
        panel.border = element_rect(linewidth = 0.5, fill = NA, color=NA))  
```

## 

# 3. ADNI

------------------------------------------------------------------------

```{r set up data ADNI}
#| echo: false
df <- read_xlsx("~/ADNI.xlsx")
df$CSF_18142 <- ifelse(df$ABETA42 > 1700, (df$PTAU_csf)/1700, (df$PTAU_csf)/df$ABETA42)

```

## 3A. VR outcome

### Boxplots VR (ADNI)

```{r boxplots vr ADNI}
df$petstat <- as.factor(df$VR)

ggplot(df, aes(x = petstat, y = PL_217_42, fill=petstat)) +
  annotate("rect", xmin = -Inf, xmax = Inf, ymin = 0.0037, ymax = 0.0074,
           fill = "grey80", alpha = 0.4) +
  geom_violin(alpha=0.3) +
  geom_hline(yintercept=0.00738, linetype="dashed", color="grey20", alpha=.8, linewidth = .35) +
  geom_hline(yintercept=0.0037, linetype="dashed", color="grey20", alpha = .8, linewidth = .35) +
  geom_quasirandom(alpha = 0.75, size = 1,shape=21, color="black", stroke=0.25) +
  scale_y_continuous(breaks = round(seq(0, 0.1, by = 0.025), 3), limits = c(0, 0.085)) +
  scale_x_discrete(labels=c("0" ="VR-","1" ="VR+")) +
  labs(x = "AD status", y = "Plasma p-tau217/AB42") +
  scale_fill_manual(values = c("#afafaf", "#c52851"), guide = "none") +
  theme_classic() +
  theme(axis.title.x = element_blank(),
        axis.title.y = element_text(size=7),
        axis.text.x = element_text(size=6),
        axis.text.y = element_text(size=6))+
  stat_compare_means(method="t.test", label="p.signif", label.x = 1.5, label.y = 0.04)

ggplot(df, aes(x = petstat, y = CSF_18142, fill=petstat)) +
  geom_violin(alpha=0.3) +
  geom_quasirandom(alpha = 0.75, size = 1,shape=21, color="black", stroke=0.25) +
  geom_hline(yintercept=0.028, linetype="dashed", color="grey20", alpha = .8, linewidth = .35) +
  scale_y_continuous(breaks = round(seq(0, 0.115, by = 0.025), 3), limits = c(0, 0.115)) +
  scale_x_discrete(labels=c("0" ="VR-","1" ="VR+")) +
  labs(x = "AD status", y = "CSF p-tau181/AB42") +
  scale_fill_manual(values = c("#afafaf", "#ea8a0f"), guide = "none") +
  theme_classic() +
  theme(axis.title.x = element_blank(),
        axis.title.y = element_text(size=7),
        axis.text.x = element_text(size=6),
        axis.text.y = element_text(size=6))+
  stat_compare_means(method="t.test", label="p.signif", label.x = 1.5, label.y = 0.04)

```

### Analyses VR AUC (ADNI)

```{r ADNI,AB-PET VR outcome}
##AUC differences with DeLong
df$petstat <- as.factor(df$VR)

#| echo: false
biomarkers <- c("PL_217_42","ptau217", "CSF_18142")
results_delong <- list()
index <- 1

library(pROC)

for (i in seq_along(biomarkers)){
  for (j in seq_along(biomarkers)){ 
    if (i < j) {
      predictor1 <- biomarkers[i]
      predictor2 <- biomarkers[j]
      
      formula1 <- as.formula(paste("petstat~",predictor1, collapse=""))
      formula2 <- as.formula(paste("petstat~",predictor2, collapse=""))
      
      roc_curve1 <- pROC::roc(formula1, data=df, quiet=T)
      roc_curve2 <- pROC::roc(formula2, data=df,quiet=T)
      
      res <- roc.test(roc_curve1, roc_curve2, method = "delong")
      
      long <- data.frame(
        comp = paste(predictor1, predictor2, sep=" vs. "),
        auc1a = round(roc_curve1$auc,3),
        auc2a = round(roc_curve2$auc,3),
        pval = round(res$p.value,3),
        auc1_ci_low = round(ci.auc(roc_curve1)[1],3),
        auc1_ci_high =round(ci.auc(roc_curve1)[3],3),
        auc2_ci_low =round(ci.auc(roc_curve2)[1],3),
        auc2_ci_high = round(ci.auc(roc_curve2)[3],3)
      )
      
      results_delong[[length(results_delong) + 1]] <- long
      index <- index + 1
    }
  }
}

results_delong <- do.call(rbind.data.frame, results_delong)
results_delong$padj <- round(p.adjust(results_delong$pval, method = "fdr"),3)
results_delong$auc_order <- c(results_delong$auc1a[1],results_delong$auc1a[3], results_delong$auc2a[3])
results_delong$auc_order_ci_low <- c(results_delong$auc1_ci_low[1],results_delong$auc1_ci_low[3], results_delong$auc2_ci_low[3])
results_delong$auc_order_ci_high <- c(results_delong$auc1_ci_high[1],results_delong$auc1_ci_high[3], results_delong$auc2_ci_high[3])
openxlsx::write.xlsx(results_delong,
                     file="~/DELONG_VR.xlsx")

##AUC plot
roc_curve2<- pROC::roc(petstat ~ ptau217, data=df,quiet=T)
auc2 <- auc(roc_curve2)
roc_curve1 <- pROC::roc(petstat ~ PL_217_42, data=df,quiet=T)
auc1 <- auc(roc_curve1)
roc_curve3 <- pROC::roc(petstat ~ CSF_18142, data=df,quiet=T)
auc3 <- auc(roc_curve3)

roc_list <- list(roc_curve1, roc_curve2, roc_curve3)

ggroc(roc_list) +
  scale_color_manual(values = c("#c52851", "#4ca481", "#ea8a0f"), 
                     labels = c("Plasma p-tau217/AB42", "Plasma p-tau217", "CSF p-tau181/AB42"), guide="none") +
  labs(title = element_blank(), x = "Specificity", y = "Sensitivity", color = "Assay") +
  scale_x_reverse()+
  scale_y_continuous()+
  geom_abline(slope = 1, intercept = 1, linetype = "dashed") +
  theme_classic()+
  theme(panel.border = element_blank(),
        axis.text.y = element_text(size = 5,color="grey30"),
        axis.text.x = element_text(size = 5,color="grey30"),
        axis.title.x = element_text(size=6,color="black"),
        axis.title.y = element_text(size=6),color="black")+
  annotate("text", x=0.3, y=0.25, 
           label = sprintf("%.2f (%.2f, %.2f)", auc(roc_curve1), ci.auc(roc_curve1)[1], ci.auc(roc_curve1)[3]),
           size = 2, color = "#c52851")+
  annotate("text", x=0.3, y=0.15, 
           label = sprintf("%.2f (%.2f, %.2f)", auc(roc_curve2), ci.auc(roc_curve2)[1], ci.auc(roc_curve2)[3]),
           size = 2, color = "#4ca481")+
  annotate("text", x=0.3, y=0.05, 
           label = sprintf("%.2f (%.2f, %.2f)", auc(roc_curve3), ci.auc(roc_curve3)[1], ci.auc(roc_curve3)[3]),
           size = 2, color = "#ea8a0f")


```

### Metrics VR (ADNI)

```{r metrics ADNI}
df$petstat <- as.factor(df$VR)

df$ptau217ab42_pos <- ifelse(df$PL_217_42 >= 0.00738, 1, 0) 

df$csf_pos <- ifelse(df$CSF_18142 > 0.028, 1, 0)

###A. Metric comps FDA----
f_comp_stats <- function(data, indices) {
  d <- as.data.frame(data[indices,])
  
  ##threshold calculation related to d, and then assign binary status based on that threshold
  compute_metrics <- function(true, pred) {
    
    ##threshold calculation and 
    
    v_tp <- sum(true == 1 & pred == 1)
    v_fp <- sum(true == 0 & pred == 1)
    v_tn <- sum(true == 0 & pred == 0)
    v_fn <- sum(true == 1 & pred == 0)
    
    sens <- v_tp / (v_tp + v_fn)
    spec <- v_tn / (v_tn + v_fp)
    acc <- (v_tp + v_tn) / (v_tp + v_tn + v_fn + v_fp)
    ppv <- cutpointr::ppv(tp = v_tp, fp = v_fp, tn = v_tn, fn = v_fn)
    npv <- cutpointr::npv(tp = v_tp, fp = v_fp, tn = v_tn, fn = v_fn)
    
    return(c(acc, ppv, npv, sens, spec, v_tp, v_fp, v_tn, v_fn))#sens#spec
  }
  
  test_columns <- c("ptau217ab42_pos", "csf_pos")
  results <- matrix(nrow = length(test_columns), ncol = 9)
  colnames(results) <- c("Accuracy", "PPV", "NPV", "Sensitivity", "Specificity", "TP", "FP", "TN", "FN")
  rownames(results) <- c("PL_217_42", "CSF_18142")
  
  for (i in seq_along(test_columns)) {
    results[i, ] <- round(compute_metrics(d$petstat, d[[test_columns[i]]]),3)
  }
  
  #Assign p-tau217/AB42 metrics
  acc1 <- results[1,1]
  ppv1 <- results[1,2]
  npv1 <- results[1,3]
  sens1 <- results[1,4]
  spec1 <- results[1,5]
  tp1 <- results[1,6]
  fp1 <- results[1,7]
  tn1 <- results[1,8]
  fn1 <- results[1,9]
  
  #Assign CSF metrics
  acc2 <- results[2,1]
  ppv2 <- results[2,2]
  npv2 <- results[2,3]
  sens2 <- results[2,4]
  spec2 <- results[2,5]
  tp2 <- results[2,6]
  fp2 <- results[2,7]
  tn2 <- results[2,8]
  fn2 <- results[2,9]
  
  #p-tau217 vs. 217/ab42
  diff_acc <- acc1 - acc2
  diff_ppv <- ppv1 - ppv2
  diff_npv <- npv1 - npv2
  diff_sens <- sens1 - sens2
  
  
  return(c(acc1, acc2, ppv1, ppv2, npv1, npv2,#6
           diff_acc, diff_ppv, diff_npv, diff_sens,#10
           sens1, sens2, spec1, spec2, diff_sens, #15
           tp1, fp1, tn1, fn1, tp2, fp2, tn2, fn2)) #23
}   

set.seed(12345)
boot_results <- boot(data = df, statistic = f_comp_stats, R = 2000)

#Calculate pvalues 1 cutoff
stat_indices <- list(
  "Accuracy 217_AB42 vs. CSF" = 7,
  "PPV 217_AB42 vs. CSF" = 8,
  "NPV 217_AB42 vs. CSF" = 9)

pvals_1cp <- data.frame(
  Pval = numeric(length(stat_indices)),
  row.names = c("Accuracy 217_AB42 vs. CSF","PPV 217_AB42 vs. CSF","NPV 217_AB42 vs. CSF"))

bootstrap_replicates <- boot_results$t
for (stat_name in names(stat_indices)) {
  index <- stat_indices[[stat_name]]
  boot_diff <- boot_results$t0[index]
  results_underH0_diff <- bootstrap_replicates[, index] - mean(bootstrap_replicates[, index])
  p_value <- mean(abs(results_underH0_diff) >= abs(boot_diff))
  pvals_1cp[paste0(stat_name), "Pval"] <- round(p_value, 3)
}

##Add outcomes to dataframe (function to establish dataframe as desired)
create_df <- function(method_name, boot_acc_index, boot_ppv_index, boot_npv_index, boot_sen_index, boot_spec_index,boot_tp_index,boot_fp_index,boot_tn_index,boot_fn_index) {
  data.frame(
    method = method_name,
    accuracy = round(boot_results$t0[boot_acc_index], 3),
    acc_ci_lower = round(quantile(boot_results$t[, boot_acc_index], c(0.025, 0.975), na.rm=T)[1], 3),
    acc_ci_upper = round(quantile(boot_results$t[, boot_acc_index], c(0.025, 0.975), na.rm=T)[2], 3),
    PPV = round(boot_results$t0[boot_ppv_index], 3),
    ppv_ci_lower = round(quantile(boot_results$t[, boot_ppv_index], c(0.025, 0.975), na.rm=T)[1], 3),
    ppv_ci_upper = round(quantile(boot_results$t[, boot_ppv_index], c(0.025, 0.975), na.rm=T)[2], 3),
    NPV = round(boot_results$t0[boot_npv_index], 3),
    npv_ci_lower = round(quantile(boot_results$t[, boot_npv_index], c(0.025, 0.975), na.rm=T)[1], 3),
    npv_ci_upper = round(quantile(boot_results$t[, boot_npv_index], c(0.025, 0.975), na.rm=T)[2], 3),
    Sensitivity =round(boot_results$t0[boot_sen_index], 3),
    sen_ci_lower = round(quantile(boot_results$t[, boot_sen_index], c(0.025, 0.975), na.rm=T)[1], 3),
    sen_ci_upper = round(quantile(boot_results$t[, boot_sen_index], c(0.025, 0.975), na.rm=T)[2], 3),
    Specificity = round(boot_results$t0[boot_spec_index], 3),
    spec_ci_lower = round(quantile(boot_results$t[, boot_spec_index], c(0.025, 0.975), na.rm=T)[1], 3),
    spec_ci_upper = round(quantile(boot_results$t[, boot_spec_index], c(0.025, 0.975), na.rm=T)[2], 3),
    TP = round(boot_results$t0[boot_tp_index], 0),
    FP = round(boot_results$t0[boot_fp_index], 0),
    TN = round(boot_results$t0[boot_tn_index], 0),
    FN = round(boot_results$t0[boot_fn_index], 0),
    intermediate_n_percentage = NA,
    intermediate_n_percentage_low = NA,
    intermediate_n_percentage_high = NA,
    stringsAsFactors = FALSE,
    row.names = "1 Cutpoint"
  )
}

results_1cp_2 <- create_df(method_name = "Plasma p-tau217/AB42",boot_acc_index = 1,boot_ppv_index = 3,boot_npv_index = 5, boot_sen_index=11, boot_spec_index=13,boot_tp_index = 16, boot_fp_index=17, boot_tn_index=18, boot_fn_index=19)

results_1cp_3 <- create_df(method_name = "CSF p-tau181/AB42",boot_acc_index = 2,boot_ppv_index = 4,boot_npv_index = 6, boot_sen_index=12, boot_spec_index=14,boot_tp_index = 20, boot_fp_index=21, boot_tn_index=22, boot_fn_index=23)

merged_results_1cp <- rbind(results_1cp_2, results_1cp_3)

#Step 4: Bind all datasets together
merged_comps_bf <- merged_results_1cp
merged_comps_bf$Cutpoints <- c("1 Cutpoint","1 Cutpoint")
openxlsx::write.xlsx(merged_comps_bf,file="~/Results.xlsx", rowNames =T)

openxlsx::write.xlsx(pvals_1cp,file="~/Results_pvals.xlsx", rowNames =T)


#Step 5: Create dataframe for manuscript tables
table_df <- data.frame(
Measure = merged_comps_bf$method,
Accuracy = sprintf("%.2f (%.2f-%.2f)", merged_comps_bf$accuracy, merged_comps_bf$acc_ci_lower, merged_comps_bf$acc_ci_upper),
PPV = sprintf("%.2f (%.2f-%.2f)", merged_comps_bf$PPV, merged_comps_bf$ppv_ci_lower, merged_comps_bf$ppv_ci_upper),
NPV = sprintf("%.2f (%.2f-%.2f)", merged_comps_bf$NPV, merged_comps_bf$npv_ci_lower, merged_comps_bf$npv_ci_upper),
Gre= sprintf("%.2f (%.2f-%.2f)", merged_comps_bf$intermediate_n_percentage, merged_comps_bf$intermediate_n_percentage_low, merged_comps_bf$intermediate_n_percentage_high),
Sensitivity = sprintf("%.2f (%.2f-%.2f)", merged_comps_bf$Sensitivity, merged_comps_bf$sen_ci_lower, merged_comps_bf$sen_ci_upper),
Specificity =sprintf("%.2f (%.2f-%.2f)", merged_comps_bf$Specificity, merged_comps_bf$spec_ci_lower, merged_comps_bf$spec_ci_upper), 
TP =sprintf("%.2f", merged_comps_bf$TP),
FP =sprintf("%.2f", merged_comps_bf$FP),
TN =sprintf("%.2f", merged_comps_bf$TN), 
FN =sprintf("%.2f", merged_comps_bf$FN))

openxlsx::write.xlsx(table_df,file="~/Results_table.xlsx", rowNames =T)

```

### Metric figures VR (ADNI)

```{r metric figures VR ADNI}
##1 Cutoff
merged_comps_bf <- read_xlsx("~/Results.xlsx")
merged_comps_bf <- merged_comps_bf[,2:24]

##Assemble plot data in way required for plots
plot_acc <- cbind(merged_comps_bf[0:2, 1], merged_comps_bf[0:2,2:4])
colnames(plot_acc) <- c("Method", "Measure1", "ci_low", "ci_high")
plot_acc$Measure <- c("Accuracy", "Accuracy")

plot_ppv <- cbind(merged_comps_bf[0:2, 1], merged_comps_bf[0:2,5:7])
colnames(plot_ppv) <- c("Method", "Measure1", "ci_low", "ci_high")
plot_ppv$Measure <- c("PPV", "PPV")

plot_npv <- cbind(merged_comps_bf[0:2, 1], merged_comps_bf[0:2,8:10])
colnames(plot_npv) <- c("Method", "Measure1", "ci_low", "ci_high")
plot_npv$Measure <- c("NPV", "NPV")

plotdata <- rbind(plot_acc, plot_ppv, plot_npv)
plotdata1 <- plotdata
plotdata1$Method2 <- as.factor(c("2", "1"))

group_order <- c("NPV", "PPV", "Accuracy")
tick_positions <- seq(70, 100, by = 10)

#Forest plot Acc, PPV, NPV
ggplot(data=plotdata1, aes(y = factor(Measure, levels=group_order), x = Measure1 * 100, color=Method2, fill=Method2))+
  geom_vline(xintercept = tick_positions, color = "grey80", linewidth = 0.5, alpha=0.4) +
  geom_errorbar(aes(xmin = ci_low * 100, xmax = ci_high * 100),
                width = 0, linewidth = 0.75, position = position_dodge(width = 0.6)) +
  geom_point(position = position_dodge(width = 0.6), size = 1.75, stroke = 0.7)+
  scale_x_continuous(limits=c(70,110),breaks = seq(70,110, by=10),expand =c(0,0))+
  labs(x = "Percentage", y = "") +
  geom_text(aes(label = sprintf("%.f (%.f-%.f)", Measure1 * 100, ci_low * 100, ci_high * 100), group=Method2, x=106),
            position = position_dodge(width = 0.6), size = 2) +
  scale_color_manual(values=c("#4dbbd6", "#c52851"), guide="none")+
  scale_fill_manual(values=c("#4dbbd6", "#c52851"), guide="none")+
  theme_classic()+ 
  theme(axis.text.x = element_text(size = 7,color="grey30"),
        axis.text.y = element_text(size = 7, color="black"),
        axis.title.x = element_text(size = 7,color="black"),
        axis.ticks.y = element_blank(),
        legend.text = element_text(size = 6,color="black"),  
        legend.title = element_blank(), 
        legend.position = "bottom")

```

## 3B. Centiloids 24 outcome

------------------------------------------------------------------------

### Boxplots CL (ADNI)

```{r boxplots CL ADNI}
df$petstat <- as.factor(ifelse(df$CENTILOIDS >= 24, 1, 0)) 

ggplot(df, aes(x = petstat, y = PL_217_42, fill=petstat)) +
  annotate("rect", xmin = -Inf, xmax = Inf, ymin = 0.0037, ymax = 0.0074,
           fill = "grey80", alpha = 0.4) +
  geom_violin(alpha=0.3) +
  geom_hline(yintercept=0.00738, linetype="dashed", color="grey20", alpha=.8, linewidth = .35) +
  geom_hline(yintercept=0.0037, linetype="dashed", color="grey20", alpha = .8, linewidth = .35) +
  geom_quasirandom(alpha = 0.75, size = 1,shape=21, color="black", stroke=0.25) +
  scale_y_continuous(breaks = round(seq(0, 0.1, by = 0.025), 3), limits = c(0, 0.085)) +
  scale_x_discrete(labels=c("0" ="VR-","1" ="VR+")) +
  labs(x = "AD status", y = "Plasma p-tau217/AB42") +
  scale_fill_manual(values = c("#afafaf", "#c52851"), guide = "none") +
  theme_classic() +
  theme(axis.title.x = element_blank(),
        axis.title.y = element_text(size=7),
        axis.text.x = element_text(size=6),
        axis.text.y = element_text(size=6))+
  stat_compare_means(method="t.test", label="p.signif", label.x = 1.5, label.y = 0.04)

ggplot(df, aes(x = petstat, y = CSF_18142, fill=petstat)) +
  annotate("rect", xmin = -Inf, xmax = Inf, ymin = 0.02186, ymax = 0.028,
           fill = "grey80", alpha = 0.4) +
  geom_violin(alpha=0.3) +
  geom_quasirandom(alpha = 0.75, size = 1,shape=21, color="black", stroke=0.25) +
  geom_hline(yintercept=0.028, linetype="dotted", color="grey20") +
  geom_hline(yintercept=0.02186, linetype="dotted", color="grey20") +
  scale_y_continuous(breaks = round(seq(0, 0.115, by = 0.025), 3), limits = c(0, 0.115)) +
  scale_x_discrete(labels=c("0" ="VR-","1" ="VR+")) +
  labs(x = "AD status", y = "CSF p-tau181/AB42") +
  scale_fill_manual(values = c("#afafaf", "#4dbbd6"), guide = "none") +
  theme_classic() +
  theme(axis.title.x = element_blank(),
        axis.title.y = element_text(size=7),
        axis.text.x = element_text(size=6),
        axis.text.y = element_text(size=6))+
  stat_compare_means(method="t.test", label="p.signif", label.x = 1.5, label.y = 0.04)


```

### Analyses CL24 AUC (ADNI)

```{r ADNI,AB-PET CL24 outcome}
##AUC differences with DeLong
df$petstat <- as.factor(ifelse(df$CENTILOIDS >= 24, 1, 0)) 

biomarkers <- c("PL_217_42","ptau217", "CSF_18142")
results_delong <- list()
index <- 1

library(pROC)

for (i in seq_along(biomarkers)){
  for (j in seq_along(biomarkers)){ 
    if (i < j) {
      predictor1 <- biomarkers[i]
      predictor2 <- biomarkers[j]
      
      formula1 <- as.formula(paste("petstat~",predictor1, collapse=""))
      formula2 <- as.formula(paste("petstat~",predictor2, collapse=""))
      
      roc_curve1 <- pROC::roc(formula1, data=df, quiet=T)
      roc_curve2 <- pROC::roc(formula2, data=df,quiet=T)
      
      res <- roc.test(roc_curve1, roc_curve2, method = "delong")
      
      long <- data.frame(
        comp = paste(predictor1, predictor2, sep=" vs. "),
        auc1a = round(roc_curve1$auc,3),
        auc2a = round(roc_curve2$auc,3),
        pval = round(res$p.value,3),
        auc1_ci_low = round(ci.auc(roc_curve1)[1],3),
        auc1_ci_high =round(ci.auc(roc_curve1)[3],3),
        auc2_ci_low =round(ci.auc(roc_curve2)[1],3),
        auc2_ci_high = round(ci.auc(roc_curve2)[3],3)
      )
      
      results_delong[[length(results_delong) + 1]] <- long
      index <- index + 1
    }
  }
}

results_delong <- do.call(rbind.data.frame, results_delong)
results_delong$padj <- round(p.adjust(results_delong$pval, method = "fdr"),3)
results_delong$auc_order <- c(results_delong$auc1a[1],results_delong$auc1a[3], results_delong$auc2a[3])
results_delong$auc_order_ci_low <- c(results_delong$auc1_ci_low[1],results_delong$auc1_ci_low[3], results_delong$auc2_ci_low[3])
results_delong$auc_order_ci_high <- c(results_delong$auc1_ci_high[1],results_delong$auc1_ci_high[3], results_delong$auc2_ci_high[3])
openxlsx::write.xlsx(results_delong,
                     file="~/DELONG_VR.xlsx")

##AUC plot
roc_curve2 <- pROC::roc(petstat ~ ptau217, data=df,quiet=T)
auc2 <- auc(roc_curve2)
roc_curve1 <- pROC::roc(petstat ~ PL_217_42, data=df,quiet=T)
auc1 <- auc(roc_curve1)
roc_curve3 <- pROC::roc(petstat ~ CSF_18142, data=df,quiet=T)
auc3 <- auc(roc_curve3)

roc_list <- list(roc_curve1, roc_curve2, roc_curve3)

ggroc(roc_list) +
  scale_color_manual(values = c("#c52851", "#4ca481", "#4dbbd6"), 
                     labels = c("Plasma p-tau217/AB42", "Plasma p-tau217", "CSF p-tau181/AB42"), guide="none") +
  labs(title = element_blank(), x = "Specificity", y = "Sensitivity", color = "Assay") +
  scale_x_reverse()+
  scale_y_continuous()+
  geom_abline(slope = 1, intercept = 1, linetype = "dashed") +
  theme_classic()+
  theme(panel.border = element_blank(),
        axis.text.y = element_text(size = 5,color="grey30"),
        axis.text.x = element_text(size = 5,color="grey30"),
        axis.title.x = element_text(size=6,color="black"),
        axis.title.y = element_text(size=6),color="black")+
  annotate("text", x=0.3, y=0.25, 
           label = sprintf("%.2f (%.2f, %.2f)", auc(roc_curve1), ci.auc(roc_curve1)[1], ci.auc(roc_curve1)[3]),
           size = 2, color = "#c52851")+
  annotate("text", x=0.3, y=0.15, 
           label = sprintf("%.2f (%.2f, %.2f)", auc(roc_curve2), ci.auc(roc_curve2)[1], ci.auc(roc_curve2)[3]),
           size = 2, color = "#4ca481")+
  annotate("text", x=0.3, y=0.05, 
           label = sprintf("%.2f (%.2f, %.2f)", auc(roc_curve3), ci.auc(roc_curve3)[1], ci.auc(roc_curve3)[3]),
           size = 2, color = "#4dbbd6")

```

### Metrics CL24 (ADNI)

```{r metrics CL24 ADNI}
df$petstat <- as.factor(ifelse(df$CENTILOIDS >= 24, 1, 0)) 

df$ptau217ab42_pos <- ifelse(df$PL_217_42 >= 0.00738, 1, 0) 
df$ptau217ab42_neg <- ifelse(df$PL_217_42 <= 0.00370, 0, 1)

df$csf_pos <- ifelse(df$CSF_18142 > 0.028, 1, 0)
df$csf_neg <- ifelse(df$CSF_18142 < 0.022, 0, 1)

###A. Metric comps FDA----
f_comp_stats <- function(data, indices) {
  d <- as.data.frame(data[indices,])
  
  ##threshold calculation related to d, and then assign binary status based on that threshold
  compute_metrics <- function(true, pred) {
    
    ##threshold calculation and 
    
    v_tp <- sum(true == 1 & pred == 1)
    v_fp <- sum(true == 0 & pred == 1)
    v_tn <- sum(true == 0 & pred == 0)
    v_fn <- sum(true == 1 & pred == 0)
    
    sens <- v_tp / (v_tp + v_fn)
    spec <- v_tn / (v_tn + v_fp)
    acc <- (v_tp + v_tn) / (v_tp + v_tn + v_fn + v_fp)
    ppv <- cutpointr::ppv(tp = v_tp, fp = v_fp, tn = v_tn, fn = v_fn)
    npv <- cutpointr::npv(tp = v_tp, fp = v_fp, tn = v_tn, fn = v_fn)
    
    return(c(acc, ppv, npv, sens, spec, v_tp, v_fp, v_tn, v_fn))#sens#spec
  }
  
  test_columns <- c("ptau217ab42_pos", "csf_pos")
  results <- matrix(nrow = length(test_columns), ncol = 9)
  colnames(results) <- c("Accuracy", "PPV", "NPV", "Sensitivity", "Specificity", "TP", "FP", "TN", "FN")
  rownames(results) <- c("PL_217_42", "CSF_18142")
  
  for (i in seq_along(test_columns)) {
    results[i, ] <- round(compute_metrics(d$petstat, d[[test_columns[i]]]),3)
  }
  
  #Assign p-tau217/AB42 metrics
  acc1 <- results[1,1]
  ppv1 <- results[1,2]
  npv1 <- results[1,3]
  sens1 <- results[1,4]
  spec1 <- results[1,5]
  tp1 <- results[1,6]
  fp1 <- results[1,7]
  tn1 <- results[1,8]
  fn1 <- results[1,9]
  
  #Assign CSF metrics
  acc2 <- results[2,1]
  ppv2 <- results[2,2]
  npv2 <- results[2,3]
  sens2 <- results[2,4]
  spec2 <- results[2,5]
  tp2 <- results[2,6]
  fp2 <- results[2,7]
  tn2 <- results[2,8]
  fn2 <- results[2,9]
  
  #p-tau217 vs. 217/ab42
  diff_acc <- acc1 - acc2
  diff_ppv <- ppv1 - ppv2
  diff_npv <- npv1 - npv2
  diff_sens <- sens1 - sens2
  
  
  return(c(acc1, acc2, ppv1, ppv2, npv1, npv2,#6
           diff_acc, diff_ppv, diff_npv, diff_sens,#10
           sens1, sens2, spec1, spec2, diff_sens, #15
           tp1, fp1, tn1, fn1, tp2, fp2, tn2, fn2)) #23
}   

set.seed(12345)
boot_results <- boot(data = df, statistic = f_comp_stats, R = 2000)

#Calculate pvalues 1 cutoff
stat_indices <- list(
  "Accuracy 217_AB42 vs. CSF" = 7,
  "PPV 217_AB42 vs. CSF" = 8,
  "NPV 217_AB42 vs. CSF" = 9)

pvals_1cp <- data.frame(
  Pval = numeric(length(stat_indices)),
  row.names = c("Accuracy 217_AB42 vs. CSF","PPV 217_AB42 vs. CSF","NPV 217_AB42 vs. CSF"))

bootstrap_replicates <- boot_results$t
for (stat_name in names(stat_indices)) {
  index <- stat_indices[[stat_name]]
  boot_diff <- boot_results$t0[index]
  results_underH0_diff <- bootstrap_replicates[, index] - mean(bootstrap_replicates[, index])
  p_value <- mean(abs(results_underH0_diff) >= abs(boot_diff))
  pvals_1cp[paste0(stat_name), "Pval"] <- round(p_value, 3)
}

##Add outcomes to dataframe (function to establish dataframe as desired)
create_df <- function(method_name, boot_acc_index, boot_ppv_index, boot_npv_index, boot_sen_index, boot_spec_index,boot_tp_index,boot_fp_index,boot_tn_index,boot_fn_index) {
  data.frame(
    method = method_name,
    accuracy = round(boot_results$t0[boot_acc_index], 3),
    acc_ci_lower = round(quantile(boot_results$t[, boot_acc_index], c(0.025, 0.975), na.rm=T)[1], 3),
    acc_ci_upper = round(quantile(boot_results$t[, boot_acc_index], c(0.025, 0.975), na.rm=T)[2], 3),
    PPV = round(boot_results$t0[boot_ppv_index], 3),
    ppv_ci_lower = round(quantile(boot_results$t[, boot_ppv_index], c(0.025, 0.975), na.rm=T)[1], 3),
    ppv_ci_upper = round(quantile(boot_results$t[, boot_ppv_index], c(0.025, 0.975), na.rm=T)[2], 3),
    NPV = round(boot_results$t0[boot_npv_index], 3),
    npv_ci_lower = round(quantile(boot_results$t[, boot_npv_index], c(0.025, 0.975), na.rm=T)[1], 3),
    npv_ci_upper = round(quantile(boot_results$t[, boot_npv_index], c(0.025, 0.975), na.rm=T)[2], 3),
    Sensitivity =round(boot_results$t0[boot_sen_index], 3),
    sen_ci_lower = round(quantile(boot_results$t[, boot_sen_index], c(0.025, 0.975), na.rm=T)[1], 3),
    sen_ci_upper = round(quantile(boot_results$t[, boot_sen_index], c(0.025, 0.975), na.rm=T)[2], 3),
    Specificity = round(boot_results$t0[boot_spec_index], 3),
    spec_ci_lower = round(quantile(boot_results$t[, boot_spec_index], c(0.025, 0.975), na.rm=T)[1], 3),
    spec_ci_upper = round(quantile(boot_results$t[, boot_spec_index], c(0.025, 0.975), na.rm=T)[2], 3),
    TP = round(boot_results$t0[boot_tp_index], 0),
    FP = round(boot_results$t0[boot_fp_index], 0),
    TN = round(boot_results$t0[boot_tn_index], 0),
    FN = round(boot_results$t0[boot_fn_index], 0),
    intermediate_n_percentage = NA,
    intermediate_n_percentage_low = NA,
    intermediate_n_percentage_high = NA,
    stringsAsFactors = FALSE,
    row.names = "1 Cutpoint"
  )
}

results_1cp_2 <- create_df(method_name = "Plasma p-tau217/AB42",boot_acc_index = 1,boot_ppv_index = 3,boot_npv_index = 5, boot_sen_index=11, boot_spec_index=13,boot_tp_index = 16, boot_fp_index=17, boot_tn_index=18, boot_fn_index=19)

results_1cp_3 <- create_df(method_name = "CSF p-tau181/AB42",boot_acc_index = 2,boot_ppv_index = 4,boot_npv_index = 6, boot_sen_index=12, boot_spec_index=14,boot_tp_index = 20, boot_fp_index=21, boot_tn_index=22, boot_fn_index=23)

merged_results_1cp <- rbind(results_1cp_2, results_1cp_3)

#Step 2: establish the intermediate zone

df <- df %>%
  mutate(greyzone_ptau217ab42 = case_when(
    ptau217ab42_neg == 0 ~ 1,  # sens95 equals 0
    ptau217ab42_pos == 1 ~ 3,  # spec95 equals 1
    TRUE ~ 2                     # Intermediate values
  ))

df <- df %>%
  mutate(greyzone_csf = case_when(
    csf_neg == 0 ~ 1,  # sens95 equals 0 # so when they're negative 0.072
    csf_pos == 1 ~ 3,  # spec95 equals 1 #so when they're positive even 0.058
    TRUE ~ 2                     # Intermediate values
  ))

##Function to bootstrap %intermediate
f_greyzone <- function(data, indices){
  d <- data[indices, ]
  
  test_bio <- c("PL_217_42", "CSF_18142")
  pred_pos <- c("ptau217ab42_pos", "csf_pos")
  pred_neg <- c("ptau217ab42_neg", "csf_neg")
  
  for (i in seq_along(test_bio)) {
    greyzone_col <- paste0("greyzone_", test_bio[i])
    neg_col <- pred_neg[i]
    pos_col <- pred_pos[i]
    
    d <- d %>%
      mutate(!!greyzone_col := case_when(
        !!sym(neg_col) == 0 ~ 1,  # sens95 equals 0
        !!sym(pos_col) == 1 ~ 3,  # spec95 equals 1
        TRUE ~ 2
      ))  
  }
  
  int_n_ptau217ab42 <- length(which(d$greyzone_PL_217_42 ==2))
  int_perc_ptau217ab42 <- round((length(which(d$greyzone_PL_217_42 == 2)) / nrow(d)) * 100, 3)
  
  int_n_csf <- length(which(d$greyzone_csf ==2))
  int_perc_csf <- round((length(which(d$greyzone_csf == 2)) / nrow(d)) * 100, 3)
  
  #DIFFERENCES BETWEEN ASSAYS
  diff_perc_ptau217ab42_csf <- int_perc_ptau217ab42 - int_perc_csf
  
  return(c(int_perc_ptau217ab42,int_perc_csf, diff_perc_ptau217ab42_csf))
}

set.seed(12345)
boot_results_greyzone <- boot(data = df, statistic = f_greyzone, R = 2000)

##Calculate pvalue %intermediate differences
stat_indices <- list("Int% pval p-tau217/AB42 vs.CSF" = 3)

pvals_intermediate <- data.frame(
  Pval = numeric(length(stat_indices)),
  row.names = c("Int% pval p-tau217/AB42 vs.CSF"))

bootstrap_replicates_grey <- boot_results_greyzone$t

for (stat_name in names(stat_indices)) {
  index <- stat_indices[[stat_name]]
  boot_diff <- boot_results_greyzone$t0[index]
  results_underH0_diff <- bootstrap_replicates_grey[, index] - mean(bootstrap_replicates_grey[, index])
  p_value <- mean(abs(results_underH0_diff) >= abs(boot_diff))
  pvals_intermediate[paste0(stat_name), "Pval"] <- round(p_value, 3)
}

#Step 3: Two cutoff approach

f_comp_stats_2cp <- function(data, indices) {
  d <- as.data.frame(data[indices,])
  
  
  compute_metrics <- function(d,greyzone, true, pred) {
    
    dx <- d %>% filter(!!sym(greyzone) != 2)
    
    v_tp <- sum(dx[[true]] == 1 & dx[[pred]] == 1)
    v_fp <- sum(dx[[true]] == 0 & dx[[pred]] == 1)
    v_tn <- sum(dx[[true]] == 0 & dx[[pred]] == 0)
    v_fn <- sum(dx[[true]] == 1 & dx[[pred]] == 0)
    
    sens <- v_tp / (v_tp + v_fn)
    spec <- v_tn / (v_tn + v_fp)
    acc <- (v_tp + v_tn) / (v_tp + v_tn + v_fn + v_fp)
    ppv <- cutpointr::ppv(tp = v_tp, fp = v_fp, tn = v_tn, fn = v_fn)
    npv <- cutpointr::npv(tp = v_tp, fp = v_fp, tn = v_tn, fn = v_fn)
    
    return(c(acc, ppv, npv, sens, spec, v_tp, v_fp, v_tn, v_fn))#sens#spec
  }
  
  greyzones <- c("greyzone_ptau217ab42","greyzone_csf")
  test_columns <- c("ptau217ab42_pos", "csf_pos")
  true_label <- "petstat"
  
  results <- matrix(nrow = length(test_columns), ncol =9)
  colnames(results) <- c("Accuracy", "PPV", "NPV", "Sensitivity", "Specificity", "TP", "FP", "TN", "FN")
  rownames(results) <- c("PL_217_42", "CSF_18142")
  
  for (i in seq_along(test_columns)) {
    results[i, ] <- round(compute_metrics(d, greyzone = greyzones[i], true = true_label, pred = test_columns[i]),3)
  }
  
  #P-tau217/AB42
  acc1 <- results[1,1]
  ppv1 <- results[1,2]
  npv1 <- results[1,3]
  sens1 <- results[1,4]
  spec1 <- results[1,5]
  tp1 <- results[1,6]
  fp1 <- results[1,7]
  tn1 <- results[1,8]
  fn1 <- results[1,9]
  
  #CSF
  acc2 <- results[2,1]
  ppv2 <- results[2,2]
  npv2 <- results[2,3]
  sens2 <- results[2,4]
  spec2 <- results[2,5]
  tp2 <- results[2,6]
  fp2 <- results[2,7]
  tn2 <- results[2,8]
  fn2 <- results[2,9]
  
  #p-tau217 vs. 217/ab42
  diff_acc <- acc1 - acc2
  diff_ppv <- ppv1 - ppv2
  diff_npv <- npv1 - npv2
  diff_sens <- sens1 - sens2
  
  
  return(c(acc1, acc2, ppv1, ppv2, npv1, npv2,#6
           diff_acc, diff_ppv, diff_npv, diff_sens,#10
           sens1, sens2, spec1, spec2, diff_sens, #15
           tp1, fp1, tn1, fn1, tp2, fp2, tn2, fn2)) #23
} 

set.seed(12345)
boot_results_2cp <- boot(data = df, statistic = f_comp_stats_2cp, R = 2000)

##Calculate pvalues two cutoffs
stat_indices <- list(
  "Accuracy 217_AB42 vs. CSF" = 7,
  "PPV 217_AB42 vs. CSF" = 8,
  "NPV 217_AB42 vs. CSF" = 9)

pvals_2cp <- data.frame(
  Pval = numeric(length(stat_indices)),
  row.names = c("Accuracy 217_AB42 vs. CSF","PPV 217_AB42 vs. CSF","NPV 217_AB42 vs. CSF"))

bootstrap_replicates_2 <- boot_results_2cp$t
for (stat_name in names(stat_indices)) {
  index <- stat_indices[[stat_name]]
  boot_diff <- boot_results_2cp$t0[index]
  results_underH0_diff <- bootstrap_replicates_2[, index] - mean(bootstrap_replicates_2[, index])
  p_value <- mean(abs(results_underH0_diff) >= abs(boot_diff))
  pvals_2cp[paste0(stat_name), "Pval"] <- round(p_value, 3)
}

##Add results to dataframe
create_df_2 <- function(method_name, boot_acc_index, boot_ppv_index, boot_npv_index,boot_grey_index,boot_sen_index, boot_spec_index,boot_tp_index,boot_fp_index,boot_tn_index,boot_fn_index) {
  data.frame(
    method = method_name,
    accuracy = round(boot_results_2cp$t0[boot_acc_index], 3),
    acc_ci_lower = round(quantile(boot_results_2cp$t[, boot_acc_index], c(0.025, 0.975), na.rm=T)[1], 3),
    acc_ci_upper = round(quantile(boot_results_2cp$t[, boot_acc_index], c(0.025, 0.975), na.rm=T)[2], 3),
    PPV = round(boot_results_2cp$t0[boot_ppv_index], 3),
    ppv_ci_lower = round(quantile(boot_results_2cp$t[, boot_ppv_index], c(0.025, 0.975), na.rm=T)[1], 3),
    ppv_ci_upper = round(quantile(boot_results_2cp$t[, boot_ppv_index], c(0.025, 0.975), na.rm=T)[2], 3),
    NPV = round(boot_results_2cp$t0[boot_npv_index], 3),
    npv_ci_lower = round(quantile(boot_results_2cp$t[, boot_npv_index], c(0.025, 0.975), na.rm=T)[1], 3),
    npv_ci_upper = round(quantile(boot_results_2cp$t[, boot_npv_index], c(0.025, 0.975), na.rm=T)[2], 3),
    Sensitivity =round(boot_results_2cp$t0[boot_sen_index], 3),
    sen_ci_lower = round(quantile(boot_results_2cp$t[, boot_sen_index], c(0.025, 0.975), na.rm=T)[1], 3),
    sen_ci_upper = round(quantile(boot_results_2cp$t[, boot_sen_index], c(0.025, 0.975), na.rm=T)[2], 3),
    Specificity = round(boot_results_2cp$t0[boot_spec_index], 3),
    spec_ci_lower = round(quantile(boot_results_2cp$t[, boot_spec_index], c(0.025, 0.975), na.rm=T)[1], 3),
    spec_ci_upper = round(quantile(boot_results_2cp$t[, boot_spec_index], c(0.025, 0.975), na.rm=T)[2], 3),
    TP = round(boot_results_2cp$t0[boot_tp_index], 0),
    FP = round(boot_results_2cp$t0[boot_fp_index], 0),
    TN = round(boot_results_2cp$t0[boot_tn_index], 0),
    FN = round(boot_results_2cp$t0[boot_fn_index], 0),
    intermediate_n_percentage = round(boot_results_greyzone$t0[boot_grey_index],3),
    intermediate_n_percentage_low = round(quantile(boot_results_greyzone$t[, boot_grey_index], c(0.025, 0.975), na.rm=T)[1], 3),
    intermediate_n_percentage_high = round(quantile(boot_results_greyzone$t[, boot_grey_index], c(0.025, 0.975), na.rm=T)[2], 3),
    stringsAsFactors = FALSE,
    row.names = "2 Cutpoints"
  )
}

results_2cp_2 <- create_df_2(method_name = "Plasma p-tau217/AB42",boot_acc_index = 1,boot_ppv_index = 3,boot_npv_index = 5, boot_grey_index = 1, boot_sen_index=11, boot_spec_index=13,boot_tp_index = 16, boot_fp_index=17, boot_tn_index=18, boot_fn_index=19)

results_2cp_3 <- create_df_2(method_name = "CSF p-tau181/AB42",boot_acc_index = 2,boot_ppv_index = 4,boot_npv_index = 6, boot_grey_index = 2, boot_sen_index=12, boot_spec_index=14,boot_tp_index = 20, boot_fp_index=21, boot_tn_index=22, boot_fn_index=23)

merged_results_2cp <- rbind(results_2cp_2, results_2cp_3)

#Step 4: Bind all datasets together
merged_comps_bf <- rbind(merged_results_1cp, merged_results_2cp)
merged_comps_bf$Cutpoints <- c("1 Cutpoint","1 Cutpoint","2 Cutpoints","2 Cutpoints")
openxlsx::write.xlsx(merged_comps_bf,file="~/Results.xlsx", rowNames =T)

pvalues_all <- rbind(
  pvals_1cp,
  pvals_intermediate,
  pvals_2cp
)
openxlsx::write.xlsx(pvalues_all,file="~/Results_pvals.xlsx", rowNames =T)



#Step 5: Create dataframe for manuscript tables
table_df <- data.frame(
Measure = merged_comps_bf$method,
Accuracy = sprintf("%.2f (%.2f-%.2f)", merged_comps_bf$accuracy, merged_comps_bf$acc_ci_lower, merged_comps_bf$acc_ci_upper),
PPV = sprintf("%.2f (%.2f-%.2f)", merged_comps_bf$PPV, merged_comps_bf$ppv_ci_lower, merged_comps_bf$ppv_ci_upper),
NPV = sprintf("%.2f (%.2f-%.2f)", merged_comps_bf$NPV, merged_comps_bf$npv_ci_lower, merged_comps_bf$npv_ci_upper),
Gre= sprintf("%.2f (%.2f-%.2f)", merged_comps_bf$intermediate_n_percentage, merged_comps_bf$intermediate_n_percentage_low, merged_comps_bf$intermediate_n_percentage_high),
Sensitivity = sprintf("%.2f (%.2f-%.2f)", merged_comps_bf$Sensitivity, merged_comps_bf$sen_ci_lower, merged_comps_bf$sen_ci_upper),
Specificity =sprintf("%.2f (%.2f-%.2f)", merged_comps_bf$Specificity, merged_comps_bf$spec_ci_lower, merged_comps_bf$spec_ci_upper), 
TP =sprintf("%.2f", merged_comps_bf$TP),
FP =sprintf("%.2f", merged_comps_bf$FP),
TN =sprintf("%.2f", merged_comps_bf$TN), 
FN =sprintf("%.2f", merged_comps_bf$FN))

openxlsx::write.xlsx(table_df,file="~/Results_table.xlsx", rowNames =T)
```

### Metric figures CL (ADNI)

```{r metric figures CL ADNI}
##1 Cutoff
merged_comps_bf <- read_xlsx("~/Results.xlsx")
merged_comps_bf <- merged_comps_bf[,2:24]

##Assemble plot data in way required for plots
plot_acc <- cbind(merged_comps_bf[0:2, 1], merged_comps_bf[0:2,2:4])
colnames(plot_acc) <- c("Method", "Measure1", "ci_low", "ci_high")
plot_acc$Measure <- c("Accuracy", "Accuracy")

plot_ppv <- cbind(merged_comps_bf[0:2, 1], merged_comps_bf[0:2,5:7])
colnames(plot_ppv) <- c("Method", "Measure1", "ci_low", "ci_high")
plot_ppv$Measure <- c("PPV", "PPV")

plot_npv <- cbind(merged_comps_bf[0:2, 1], merged_comps_bf[0:2,8:10])
colnames(plot_npv) <- c("Method", "Measure1", "ci_low", "ci_high")
plot_npv$Measure <- c("NPV", "NPV")

plotdata <- rbind(plot_acc, plot_ppv, plot_npv)
plotdata1 <- plotdata
plotdata1$Method2 <- as.factor(c("2", "1"))

group_order <- c("NPV", "PPV", "Accuracy")
tick_positions <- seq(70, 100, by = 10)

#Forest plot Acc, PPV, NPV
ggplot(data=plotdata1, aes(y = factor(Measure, levels=group_order), x = Measure1 * 100, color=Method2, fill=Method2))+
  geom_vline(xintercept = tick_positions, color = "grey80", linewidth = 0.5, alpha=0.4) +
  geom_errorbar(aes(xmin = ci_low * 100, xmax = ci_high * 100),
                width = 0, linewidth = 0.75, position = position_dodge(width = 0.6)) +
  geom_point(position = position_dodge(width = 0.6), size = 1.75, stroke = 0.7)+
  scale_x_continuous(limits=c(70,110),breaks = seq(70,110, by=10),expand =c(0,0))+
  labs(x = "Percentage", y = "") +
  geom_text(aes(label = sprintf("%.f (%.f-%.f)", Measure1 * 100, ci_low * 100, ci_high * 100), group=Method2, x=106),
            position = position_dodge(width = 0.6), size = 2) +
  scale_color_manual(values=c("#4dbbd6", "#c52851"), guide="none")+
  scale_fill_manual(values=c("#4dbbd6", "#c52851"), guide="none")+
  theme_classic()+ 
  theme(axis.text.x = element_text(size = 7,color="grey30"),
        axis.text.y = element_text(size = 7, color="black"),
        axis.title.x = element_text(size = 7,color="black"),
        axis.ticks.y = element_blank(),
        legend.text = element_text(size = 6,color="black"),  
        legend.title = element_blank(), 
        legend.position = "bottom")


```
